companieshouse/acsp-web

- src/routers/handlers/kick-out/stopNotRelevantOfficer.ts
- src/routers/handlers/role/statementRelevantOfficer.ts
- src/views/layouts/default.njk
- Added back button to all screens.
- Added placeholder back urls to screens that do not have the precious screen developed.
> Added back button to all screens.

- package-lock.json
- package.json
- src/lib/utils/error_manifests/sectorYouWorkIn.ts
- src/lib/validation/sectorYouWorkIn.ts
- src/lib/validation/validation.ts
- src/router.dispatch.ts
- src/routers/setorYouWorkInRouter.ts
- src/views/layouts/default.njk
- src/views/partials/error_summary.njk
- src/views/router_views/sector-you-work-in/sector-you-work-in.njk
- test/src/routers/sectorYouWorkInRouter.test.ts
Add new screen for 'which sector do you work in'
Add express-validator for validation
> which sector do you work in

- src/views/router_views/sector-you-work-in/sector-you-work-in.njk
fix double question marks issue
> fix double question marks issue

- src/views/router_views/sector-you-work-in/sector-you-work-in.njk
> fix accecibility issue

- src/main/views/partials/country-typeahead-noscript-input.njk
Change to make countries display correctly when JS is disabled
> Change to make countries display correctly when JS is disabled

- config/.env
- lib/validation/sectorYouWorkIn.ts
- lib/validation/validation.ts
- locales/cy/common-errors.json
- locales/cy/common.json
- locales/cy/sector-you-work-in.json
- locales/en/common-errors.json
- locales/en/common.json
- locales/en/sector-you-work-in.json
- package-lock.json
- package.json
- src/main/app.ts
- src/main/controllers/features/SoleTrader/sectorYouWorkInController.ts
- src/main/routes/index.ts
- src/main/types/pageURL.ts
- src/main/utils/localise.ts
- src/main/utils/properties.ts
- src/main/views/features/sole-trader/sector-you-work-in/sector-you-work-in.njk
- src/main/views/layouts/default.njk
- src/main/views/partials/__meta_header.njk
- src/main/views/partials/error_summary.njk
changes for localisation.
translation for sector you work in
> changes for localisation

- package-lock.json
- package.json
- sonar-project.properties
- src/main/routes/index.ts
Added sonar-project.properties
> IDVA5-494-adding-dependencies

- src/main/views/features/sole-trader/correspondance-address-manual/capture-correspondance-address-manual.njk
- src/main/views/features/sole-trader/date-of-birth/capture-date-of-birth.njk
- src/main/views/features/sole-trader/sector-you-work-in/sector-you-work-in.njk
- src/main/views/partials/user_name.njk
Making Required changes for Firstname and Lastname
> Req-Changes-for-IDVA5-456

- src/main/views/features/sole-trader/type-of-business/type-of-business.njk
corrected the order of the radio buttons,
fixed error at field level
> corrected the order of the radio buttons

- src/main/controllers/features/SoleTrader/soleTradercorrespondenceAddressConfirmController.ts
- src/main/views/features/sole-trader/correspondence-address-confirm/correspondence-address-confirm.njk
> Required Changes for Address Confirm Page 

- ecs-image-build/Dockerfile
- ecs-image-build/docker_start.sh
> Fixing ECS build

- Makefile
- ecs-image-build/Dockerfile
- ecs-image-build/docker_start.sh
> Add dist folder

- src/main/utils/properties.ts
- src/test/src/setup.ts
> add CDN_URL_CSS

- src/main/validation/correspondenceAddressAutoLookup.ts
Replacing error message with correct error message
> IDVA5-567-required-change-for-correspondenceAddressAutoLookup-error

- src/main/controllers/features/SoleTrader/indexController.ts
- src/main/controllers/features/SoleTrader/otherTypeOfBusinessController.ts
- src/main/controllers/features/SoleTrader/soleTraderCorrespodanceAddressDetailsController.ts
- src/main/controllers/features/limited/businessMustbeAmlRegisteredController.ts
- src/main/controllers/features/limited/companyInactiveController.ts
- src/main/controllers/features/limited/nameRegisteredWithAmlController.ts
- src/main/views/partials/__meta_header.njk
Correcting all the titles. Also making necessary change in header.njk for home page.
> IDVA5-550-review-page-title

- src/main/controllers/features/SoleTrader/indexController.ts
- src/main/controllers/features/SoleTrader/otherTypeOfBusinessController.ts
- src/main/controllers/features/SoleTrader/soleTraderCorrespodanceAddressDetailsController.ts
- src/main/controllers/features/limited/businessMustbeAmlRegisteredController.ts
- src/main/controllers/features/limited/companyInactiveController.ts
- src/main/controllers/features/limited/nameRegisteredWithAmlController.ts
- src/main/views/partials/__meta_header.njk
Reverts companieshouse/acsp-web#117
> Revert "IDVA5-550-review-page-title"

- src/main/controllers/features/SoleTrader/indexController.ts
- src/main/controllers/features/SoleTrader/otherTypeOfBusinessController.ts
- src/main/controllers/features/SoleTrader/soleTraderCorrespodanceAddressDetailsController.ts
- src/main/controllers/features/limited/businessMustbeAmlRegisteredController.ts
- src/main/controllers/features/limited/companyInactiveController.ts
- src/main/controllers/features/limited/nameRegisteredWithAmlController.ts
- src/main/views/partials/__meta_header.njk
Correcting page titles and making required changes for home page title.
> IDVA5-550-Correcting Page titles

- src/main/app.ts
- src/test/src/controllers/healthCheckController.test.ts
- src/test/src/controllers/indexController.test.ts
Changing RegEx to avoid authentication on healthcheck and home page
> Changing RegEx to avoid authentication on healthcheck and home page

- src/main/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
First name, last name to come over h1 in Where do you live screen.
> First name, last name to come over h1

- src/main/validation/nationality.ts
- fix for wrong validation messaged displaying in the nationality page screen
> validation messaged  fixed

- src/main/validation/nationality.ts
-add nationality validation fix
> -Fix validation bug

- locales/cy/company-number.json
- src/main/views/features/limited/company-number/company-number.njk
> add open tab feauture

- locales/cy/stop-not-relevant-officer.json
- locales/en/stop-not-relevant-officer.json
- src/main/views/features/sole-trader/stop-not-relevant-officer/stop-not-relevant-officer.njk
Required change for translation
> IDVA5-161-Required change for translation

- src/main/views/features/sole-trader/nationality/nationality.njk
-Fix input issues on disabled JS page
> -fix input issues

- src/main/views/partials/cookie_consent_banner.njk
fix to open view cookies link in new tab
> fix to open link in new tab

- src/main/controllers/features/SoleTrader/indexController.ts
Updated "Start now" button on home page to pass language to the next page
> Home page localisation update

- src/main/controllers/features/SoleTrader/typeOfBusinessController.ts
Adding a condition before creating a transaction otherwise everytime a new transaction is getting created.
> Adding a condition before creating a transaction

- src/main/controllers/features/SoleTrader/typeOfBusinessController.ts
- src/main/services/company/company_profile_service.ts
- src/main/services/companyLookupService.ts
Adding a logger statement for company profile
> Adding a logger statement

- src/main/router.dispatch.ts
- src/main/types/pageURL.ts
- src/main/views/features/sole-trader/correspondence-auto-lookup-address/auto-lookup-address.njk
- src/main/views/features/sole-trader/correspondence-auto-lookup-address/correspondence-address-list.njk
- src/main/views/partials/__footer.njk
- src/main/views/partials/__header.njk
- src/test/e2e/features/stopnotrelevantofficerRouter.ts
- src/test/src/controllers/indexController.test.ts
- src/test/src/controllers/otherTypeOfBusinessController.test.ts
- src/test/src/controllers/soleTradercorrespondenceAddressConfirmController.test.ts
- terraform/groups/ecs-service/locals.tf
Home page URL updated to  /register-as-companies-house-authorised-agent
Context path updated to “/register-as-companies-house-authorised-agent”
+ some other minor url fixes
> page urls bug fix

- locales/cy/common.json
- locales/en/common.json
- src/main/views/layouts/default.njk
- src/test/mocks/session_middleware_mock.ts
localisation for "Back" button
> IDVA5-616-localisation-for-back-button

- src/main/controllers/features/SoleTrader/soleTraderCorrespodanceAddressDetailsController.ts
- src/main/views/features/sole-trader/correspondence-auto-lookup-address/auto-lookup-address.njk
- src/main/views/features/sole-trader/correspondence-auto-lookup-address/correspondence-address-list.njk
- src/main/views/features/sole-trader/nationality/nationality.njk
- src/main/views/features/sole-trader/other-type-of-business/other-type-of-business.njk
- src/main/views/features/sole-trader/type-of-business/type-of-business.njk
Adding username for correspondence address list screen and correcting other njks. Calling name from partials user_name njk
> IDVA5-587-username-for-address-list-screen

- src/main/config/index.ts
- src/main/controllers/features/SoleTrader/otherTypeOfBusinessController.ts
- src/main/controllers/features/SoleTrader/typeOfBusinessController.ts
- src/main/controllers/features/limited/nameRegisteredWithAmlController.ts
- src/main/routes/index.ts
- src/main/types/pageURL.ts
- src/test/src/controllers/otherTypeOfBusinessController.test.ts
- src/test/src/controllers/sectorYouWorkInController.test.ts
- src/test/src/controllers/typeOfBusinessController.test.ts
Updating routing for which type of business are you registering screen also formatting
> IDVA5-634-update-routing-for-type-of-business-you-registering

- src/main/config/index.ts
- src/main/controllers/features/SoleTrader/sectorYouWorkInController.ts
- src/main/types/pageURL.ts
- src/main/views/common/sector-you-work-in/sector-you-work-in.njk
Make changes to sole trader - which sector you work in, to redirect to correct pages. Username to appear on the top. Refactored to make the view reusable in other journeys. No unit tests written as its already there.
> which sector changes

- src/main/common/__utils/constants.ts
- src/main/controllers/features/unincorporated/unincorporatedNameRegisteredWithAmlController.ts
- src/main/controllers/features/unincorporated/whatIsTheBusinessNameController.ts
Correcting back pages for Unincorporated journey What is the business name? screen
> IDVA5-618-back-button-logic-for-business-name-screen

- src/main/controllers/features/SoleTrader/soleTraderCorrespodanceAddressDetailsController.ts
- src/main/controllers/features/SoleTrader/soleTraderCorrespondenceAddressAutoLookupController.ts
- src/main/views/features/sole-trader/correspondence-auto-lookup-address/auto-lookup-address.njk
- src/main/views/features/sole-trader/correspondence-auto-lookup-address/correspondence-address-list.njk
- src/main/views/partials/__header.njk
Fixed bugs related to Page urls.
> pageurls-fixbugs

- terraform/groups/ecs-service/locals.tf
> pageUrls - fix context path in tf files

- src/main/types/pageURL.ts
- src/test/mocks/all_middleware_mock.ts
- src/test/mocks/session_middleware_mock.ts
- src/test/src/controllers/isThisYourCompanyController.test.ts
Fixing the way session data is mocked for different cases
> Fixing the way session data is mocked for different cases

- src/main/controllers/features/limited/whichSectorOtherController.ts
> fixed the current url

- sonar-project.properties
Add reference branch as main for sonar
> Add reference branch for sonar

- src/main/controllers/features/limited/isThisYourCompanyController.ts
- src/main/controllers/features/limited/whatIsYourRoleController.ts
- src/main/routes/index.ts
- src/main/services/company-details/companyDetailsService.ts
- src/test/src/controllers/isThisYourCompanyController.test.ts
- src/test/src/middleware/company_authentication_middleware.test.ts
integrate company auth code screen
> integrate company auth code screen

- sonar-project.properties
Removing base reference branch
> Removing base reference branch

- src/main/controllers/features/sole-trader/whichSectorOtherController.ts
- src/main/controllers/features/unincorporated/unincorporatedSectorYouWorkInController.ts
- src/main/controllers/features/unincorporated/whichSectorOtherController.ts
- src/main/controllers/index.ts
- src/main/routes/index.ts
- src/main/types/pageURL.ts
- src/test/src/controllers/unincorporatedWhichSectorOtherController.test.ts
add screen for unincorporated which sector other
> add screen for unincorporated which sector other

- src/main/app.ts
- src/main/common/__utils/session.ts
- src/main/controllers/accessibilityStatementController.ts
- src/main/controllers/features/common/stopNotRelevantOfficerController.ts
- src/main/controllers/features/limited/businessMustbeAmlRegisteredController.ts
- src/main/controllers/features/limited/companyInactiveController.ts
- src/main/controllers/features/limited/nameRegisteredWithAmlController.ts
- src/main/controllers/features/limited/sectorYouWorkInController.ts
- src/main/controllers/features/limited/whatIsYourRoleController.ts
- src/main/controllers/features/sole-trader/correspodanceAddressDetailsController.ts
- src/main/controllers/features/sole-trader/correspondenceAddressAutoLookupController.ts
- src/main/controllers/features/sole-trader/correspondenceAddressConfirmController.ts
- src/main/controllers/features/sole-trader/correspondenceAddressManualController.ts
- src/main/controllers/features/sole-trader/dateOfBirthController.ts
- src/main/controllers/features/sole-trader/nameController.ts
- src/main/controllers/features/sole-trader/nationalityController.ts
- src/main/controllers/features/sole-trader/otherTypeOfBusinessController.ts
- src/main/controllers/features/sole-trader/sectorYouWorkInController.ts
- src/main/controllers/features/sole-trader/typeOfBusinessController.ts
- src/main/controllers/features/sole-trader/whatIsTheBusinessNameController.ts
- src/main/controllers/features/sole-trader/whereDoYouLiveController.ts
- src/main/controllers/features/sole-trader/whichSectorOtherController.ts
- src/main/controllers/features/unincorporated/unincorporatedNameRegisteredWithAmlController.ts
- src/main/controllers/features/unincorporated/unincorporatedSectorYouWorkInController.ts
- src/main/controllers/features/unincorporated/unincorporatedWhatIsYourNameController.ts
- src/main/controllers/features/unincorporated/unincorporatedWhatIsYourRoleController.ts
- src/main/controllers/features/unincorporated/whatIsTheBusinessNameController.ts
- src/main/services/company-details/companyDetailsService.ts
- src/main/validation/companyLookup.ts
> Removing Code Smells

- locales/cy/address-look-up.json
- locales/en/address-look-up.json
- src/main/common/__utils/constants.ts
- src/main/config/index.ts
- src/main/controllers/features/limited/companyLookupController.ts
- src/main/controllers/features/sole-trader/correspondenceAddressAutoLookupController.ts
- src/main/controllers/features/unincorporated/businessAddressAutoLookupController.ts
- src/main/controllers/features/unincorporated/businessAddressListController.ts
- src/main/controllers/index.ts
- src/main/model/ACSPData.ts
- src/main/routes/index.ts
- src/main/services/address/addressLookUp.ts
- src/main/services/postcode-lookup-service.ts
- src/main/types/pageURL.ts
- src/main/validation/businessAddressList.ts
- src/main/validation/correspondenceAddressAutoLookup.ts
- src/main/views/features/unincorporated/business-address-auto-lookup/auto-lookup-address.njk
- src/main/views/features/unincorporated/business-address-auto-lookup/business-address-list.njk
- src/main/views/partials/business_name.njk
- src/test/src/controllers/unincorporatedBusinessAddressListRouter.test.ts
- src/test/src/controllers/unincorporatedBusinessAddressLookUp.test.ts
- src/test/src/services/postCode-lookUp.test.ts
Added address auto lookup for unincorporated business address. 
Added business address list view after auto lookup.
Updated auto lookup validation to only call postcode API once.
> Added address auto lookup for unincorporated business address. 

- src/main/controllers/features/sole-trader/typeOfBusinessController.ts
Getting the session value directly- potential fix for  system crash
> Getting the session value directly

- locales/cy/what-is-your-role.json
- locales/en/what-is-your-role.json
- src/main/controllers/features/sole-trader/whatIsYourRoleController.ts
- src/test/src/controllers/soleTraderWhatIsYourRoleController.test.ts
- src/test/src/controllers/unincorporatedWhatIsYourRoleController.test.ts
- small text change for whats your role page
> Title change for whats role page

- src/main/controllers/features/unincorporated/businessAddressAutoLookupController.ts
- src/main/controllers/features/unincorporated/businessAddressListController.ts
- src/main/services/address/addressLookUp.ts
Calling businessName from ACSPData model
> IDVA6-177-required-changes

- locales/cy/common-address-manual.json
- locales/en/common-address-manual.json
- src/main/controllers/features/sole-trader/correspondenceAddressManualController.ts
- src/main/controllers/features/unincorporated/correspondenceAddressManualController.ts
> Title change

- locales/cy/what-is-the-business-name.json
- locales/en/what-is-the-business-name.json
- src/main/controllers/features/unincorporated/whatIsTheBusinessNameController.ts
- src/main/views/common/what-is-the-business-name/what-is-the-business-name.njk
-update h1, hint and added comment to screen
> Feature idva5 630/unincorporated] update design for 'what is the business name'

- locales/cy/common-address-manual.json
- locales/en/common-address-manual.json
- src/main/controllers/features/unincorporated/addressCorrespondanceSelectorController.ts
- src/main/controllers/features/unincorporated/correspondenceAddressAutoLookupController.ts
- src/main/controllers/features/unincorporated/correspondenceAddressListController.ts
- src/main/validation/commonAddressManual.ts
- src/main/views/features/unincorporated/business-address-auto-lookup/auto-lookup-address.njk
- src/main/views/features/unincorporated/business-address-auto-lookup/business-address-list.njk
- src/test/src/controllers/unincorporatedCorrespondenceAddressManualController.test.ts
-update business page back link
- update address validation
- added business name/name to list and manual page
> Minor changes

- src/main/views/common/correspondence-auto-lookup-address/auto-lookup-address.njk
- src/main/views/common/correspondence-auto-lookup-address/correspondence-address-list.njk
- src/main/views/features/unincorporated/address-correspondance-selector/address-correspondance-selector.njk
- src/main/views/features/unincorporated/business-address-auto-lookup/auto-lookup-address.njk
- src/main/views/features/unincorporated/business-address-auto-lookup/business-address-list.njk
fix business name not appearing bug
> fix business name not appearing bug

- locales/cy/what-is-the-business-name.json
- locales/en/what-is-the-business-name.json
- src/main/views/features/sole-trader/what-is-the-business-name/what-is-the-business-name.njk
> text name updated

- locales/cy/stop-not-relevant-officer.json
- locales/en/stop-not-relevant-officer.json
- src/main/controllers/features/unincorporated/correspondenceAddressConfirmController.ts
- src/main/controllers/features/unincorporated/unincorporatedBusinessAddressManualEntryController.ts
- src/main/controllers/features/unincorporated/unincorporatedConfirmYourBusinessAddressController.ts
- src/main/views/common/stop-not-relevant-officer/stop-not-relevant-officer.njk
- src/test/src/controllers/unicorporatedCorrespondenceAddressConfirmController.test.ts
- src/test/src/controllers/unincorporatedConfirmYourBusinessAddressController.test.ts
-update content for you cannot use this service
> -updated kick-out page

- src/main/views/features/sole-trader/nationality/nationality.njk
- src/main/views/features/sole-trader/type-of-business/type-of-business.njk
-added 2/3 class to nationality and business type page
> -resized page 2/3rd

- src/main/views/features/sole-trader/nationality/nationality.njk
-added hint class to nationality page
> -update hint nationality screen

- src/main/views/common/correspondence-auto-lookup-address/auto-lookup-address.njk
- src/main/views/common/name-registered-with-aml/name-registered-with-aml.njk
- src/main/views/features/limited/business-mustbe-aml-registered/business-mustbe-aml-registered.njk
- src/main/views/features/sole-trader/type-of-business/type-of-business.njk
-align pages to back button top left
> Feature idva5 660  body align

- src/main/views/features/sole-trader/nationality/nationality.njk
- src/main/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
> -align page to left margin

- locales/cy/what-is-your-role.json
- locales/en/what-is-your-role.json
- src/main/controllers/features/limited/whatIsYourRoleController.ts
- src/main/controllers/features/sole-trader/otherTypeOfBusinessController.ts
- src/main/controllers/features/sole-trader/typeOfBusinessController.ts
- src/main/controllers/features/sole-trader/whatIsYourRoleController.ts
- src/main/controllers/features/unincorporated/unincorporatedWhatIsYourRoleController.ts
- src/main/model/TypeOfBusiness.ts
- src/main/routes/index.ts
- src/main/validation/soleTraderWhatIsYourRole.ts
- src/main/validation/whatIsYourRole.ts
- src/main/views/common/what-is-your-role/what-is-your-role.njk
- src/test/src/controllers/limitedWhatIsYourRoleController.test.ts
- src/test/src/controllers/soleTraderWhatIsYourRoleController.test.ts
- src/test/src/controllers/unincorporatedWhatIsYourRoleController.test.ts
Setting up Error Messages on What is your Role? screen when no option is selected
> IDVA5-658-error-messages

- src/main/controllers/features/sole-trader/typeOfBusinessController.ts
- src/main/utils/feature.flag.ts
- src/main/utils/properties.ts
- src/main/views/features/sole-trader/type-of-business/type-of-business.njk
- src/test/src/controllers/soleTraderSelectAmlSupervisorController.test.ts
- src/test/src/controllers/unincorporatedSelectAmlSupervisorController.test.ts
Added couple of feature flags to showcase how we can use in the project
> example feature flags added

- package-lock.json
- package.json
- src/main/views/layouts/default.njk
- src/main/views/partials/__footer.njk
Moved govuk-frontend script to footer to fix sole trader business name
> Moved govuk-frontend script to footer to fix sole trader business name

- package-lock.json
- package.json
Fixed vulnerabilities by upgrading the formidable package and supertest package
> Fixed vulnerabilities

- locales/cy/is-this-your-company.json
- locales/en/is-this-your-company.json
- src/main/views/features/limited/is-this-your-company/is-this-your-company.njk
- small fix for check your answers and is your company page
> text added and office address removed

- locales/cy/what-is-the-business-name.json
- locales/en/what-is-the-business-name.json
- src/main/controllers/features/sole-trader/whatIsTheBusinessNameController.ts
> updated the content

- locales/cy/common-address-manual.json
- locales/en/common-address-manual.json
> Idva5 682 content change

- src/main/controllers/features/limited/isThisYourCompanyController.ts
- src/main/services/company-details/companyDetailsService.ts
- src/main/views/common/address-correspondance-selector/address-correspondance-selector.njk
- src/main/views/common/what-is-your-role/what-is-your-role.njk
- saved registered office address to session
> Address bug limited journey

- locales/cy/what-is-your-name.json
- locales/en/what-is-your-name.json
- src/main/views/common/name/capture-name.njk
Added inset text to the what is your name page
> Added inset text to the what is your name page

- src/main/controllers/features/limited/companyLookupController.ts
- src/main/controllers/features/sole-trader/typeOfBusinessController.ts
- src/main/middleware/common_variables_middleware.ts
Using user id as the id of ACSP registration data record
> Using user id as the id of ACSP registration data record

- src/main/views/features/limited/is-this-your-company/is-this-your-company.njk
-made registredofficeaddress.country optional
> -fix address bug and updating company page content

- src/main/controllers/features/common/applicationConfirmationController.ts
- src/main/views/common/application-confirmation/application-confirmation.njk
-added application number to confirm page
> -displayed transaction id on confirmation page

- src/main/controllers/features/common/typeOfBusinessController.ts
- src/main/controllers/features/limited/companyLookupController.ts
Stop calling post data temporarily
> Stop calling post data temporarily

- src/main/views/common/other-type-of-business/other-type-of-business.njk
- src/main/views/common/type-of-business/type-of-business.njk
Removed event triggers for matomo analytics - Only using the goals
> Removed event triggers for matomo analytics

- src/main/controllers/features/common/checkAmlDetailsController.ts
- src/main/controllers/features/limited/addressCorrespondanceSelectorController.ts
- src/main/views/common/check-aml-details/check-aml-details.njk
bug fix for check aml details +
bug fix for correspondence address screen - to not auto populate the data on address auto lookup page
> Bugfix check aml screens

- locales/cy/saved-application.json
- locales/en/saved-application.json
- src/main/config/index.ts
- src/main/controllers/features/common/savedApplicationController.ts
- src/main/controllers/index.ts
- src/main/routes/index.ts
- src/main/types/pageURL.ts
- src/main/validation/savedApplication.ts
- src/main/views/common/saved-application/saved-application.njk
- src/test/src/controllers/savedApplicationController.test.ts
> IDVA5-762-saved-application

- src/main/controllers/features/common/checkYourAnswers.ts
- src/main/views/common/sector-you-work-in/sector-you-work-in.njk
- src/main/views/common/what-is-your-role/what-is-your-role.njk
- Updated back URL for check your answers page
- Fixed undefined on limited Matomo analytics
> Matomo and check your answers bug fixes

- src/main/views/common/accessibility-statement/accessibility-statement.njk
- src/main/views/common/aml-body-number/aml-body-number.njk
- src/main/views/common/application-confirmation/application-confirmation.njk
- src/main/views/common/check-aml-details/check-aml-details.njk
- src/main/views/common/correspondence-address-confirm/correspondence-address-confirm.njk
- src/main/views/common/correspondence-auto-lookup-address/auto-lookup-address.njk
- src/main/views/common/index/home.njk
- src/main/views/common/name-registered-with-aml/name-registered-with-aml.njk
- src/main/views/common/name/capture-name.njk
- src/main/views/common/saved-application/saved-application.njk
- src/main/views/common/sector-you-work-in/sector-you-work-in.njk
- src/main/views/common/select-aml-supervisory-bodies/select-aml-supervisory-bodies.njk
- src/main/views/common/sign-out-page/sign-out.njk
- src/main/views/common/stop-not-relevant-officer/stop-not-relevant-officer.njk
- src/main/views/common/type-of-business/type-of-business.njk
- src/main/views/common/what-is-the-business-name/what-is-the-business-name.njk
- src/main/views/common/your-responsibilities/your-responsibilities.njk
- src/main/views/features/limited/business-mustbe-aml-registered/business-mustbe-aml-registered.njk
- src/main/views/features/limited/company-inactive/company-inactive.njk
- src/main/views/features/sole-trader/nationality/nationality.njk
- src/main/views/features/sole-trader/what-is-the-business-name/what-is-the-business-name.njk
- src/main/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
- src/main/views/features/unincorporated/business-address-auto-lookup/business-address-list.njk
- src/main/views/features/unincorporated/confirm-your-business-address/confirm-your-business-address.njk
- src/main/views/layouts/default.njk
Refactored all njk files so margins and padding are consistent across all screens
> Padding and margin fix

- src/main/controllers/features/common/checkYourAnswers.ts
- src/main/controllers/features/common/otherTypeOfBusinessController.ts
- src/main/controllers/features/common/typeOfBusinessController.ts
- src/main/controllers/features/unincorporated/unincorporatedNameRegisteredWithAmlController.ts
- src/main/views/partials/check-your-answers/unincorporated-answers.njk
- Removed change link for unincorporated role
- Fixed bug where name persists on unincorporated check your answers
- Fixed bug where data was not saving on other type of business
> Bug fixes for save and continue & check your answers

- locales/cy/application-submitted.json
- locales/en/application-submitted.json
- src/main/controllers/features/common/applicationConfirmationController.ts
- src/main/views/common/check-your-answers/check-your-answers.njk
- src/main/views/common/correspondence-address-manual/capture-correspondence-address-manual.njk
- src/main/views/features/limited/is-this-your-company/is-this-your-company.njk
- src/test/src/controllers/common/applicationConfirmationController.test.ts
- Application submitted screen now shows email address
- fixed margins on check your answers, correspondence address manual and is this your company screens
> Idva5 803 confirm page email fix

- package-lock.json
- package.json
- src/main/views/common/index/home.njk
- src/main/views/layouts/default.njk
- src/main/views/partials/__header.njk
- Updated ch-node-utils version to fix accessibility issue with language
- Small accessibility fix on home page
> Updated ch-node-utils version to fix accessiblity issue with language

- src/main/controllers/features/unincorporated/addressCorrespondanceSelectorController.ts
- src/main/controllers/features/unincorporated/unincorporatedWhatIsYourNameController.ts
- src/main/views/common/name/capture-name.njk
- src/main/views/features/sole-trader/nationality/nationality.njk
- src/main/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
- src/main/views/partials/country-typeahead-input.njk
- src/main/views/partials/country-typeahead-noscript-input.njk
- src/main/views/partials/nationality-typeahead-input.njk
- src/main/views/partials/nationality-typeahead-noscript-input.njk
- src/test/src/controllers/soleTrader/nationalityController.test.ts
- src/test/src/controllers/soleTrader/whereDoYouLiveController.test.ts
-Fixed validation errors not showing on, What is your name, What is your nationality and where do you live screens
-Fixed unincorporated what is correspondence address selector not displaying after selection
> Idva5 841 validation error bug fix

- locales/cy/check-aml-details.json
- locales/en/check-aml-details.json
> IDVA5-847   Check the Anti-Money Laundering (AML) details page fixes

- src/main/controllers/features/common/amlBodyMembershipNumberController.ts
- wrong error mesaaged amended
> Idva5 807 incorrect message AML

- package-lock.json
- src/main/controllers/features/common/resumeJourneyController.ts
- src/main/controllers/index.ts
- src/main/routes/index.ts
- src/main/types/pageURL.ts
- src/test/src/controllers/common/resumeJourneyController.test.ts
Adding resume journey controller
> Adding resume journey controller

- src/views/partials/error_404.njk
- src/views/partials/error_500.njk
Removed back link from error page and 404 pages
> Removed back link from error page and 404 pages

- src/controllers/features/common/checkSavedApplicationController.ts
- src/controllers/features/common/savedApplicationController.ts
- src/services/acspRegistrationService.ts
- test/src/controllers/common/checkSavedApplicationController.ts
- test/src/controllers/savedApplicationController.test.ts
- test/src/services/acspRegistrationService.test.ts
- Calling deleteAcspApplication from savedApplicationController
- Added unit tests for successful and unsuccessful application deletion
> Deleting old application when user choses not to continue with application

- Dockerfile
- src/controllers/features/common/amlBodyMembershipNumberController.ts
- src/services/amlSupervisoryBody/amlBodyService.ts
- test/src/services/amlBodyService.test.ts
Updated idva5 820 aml save and continue
> Updated idva5 820 aml save and continue

- locales/cy/address-look-up.json
- locales/cy/common.json
- locales/cy/is-this-your-company.json
- locales/cy/name-registered-with-aml.json
- locales/cy/what-is-the-business-name.json
- locales/en/address-look-up.json
- locales/en/common.json
- locales/en/name-registered-with-aml.json
- locales/en/what-is-the-business-name.json
- src/views/common/check-aml-details/check-aml-details.njk
- src/views/common/correspondence-address-manual/capture-correspondence-address-manual.njk
- src/views/common/name-registered-with-aml/name-registered-with-aml.njk
- src/views/common/name/capture-name.njk
- src/views/common/other-type-of-business/other-type-of-business.njk
- src/views/common/sector-you-work-in/sector-you-work-in.njk
- src/views/common/type-of-business/type-of-business.njk
- src/views/common/what-is-the-business-name/what-is-the-business-name.njk
- src/views/common/what-is-your-role/what-is-your-role.njk
- src/views/features/limited/company-number/company-number.njk
- src/views/features/limited/is-this-your-company/is-this-your-company.njk
- src/views/features/sole-trader/nationality/nationality.njk
- src/views/features/sole-trader/what-is-your-date-of-birth/what-is-your-date-of-birth.njk
- src/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
- Updated save buttons to save and continue buttons.
- Removed duplicate save and continue buttons
> Updated save buttons to save and continue buttons

- locales/cy/saved-application.json
- locales/en/saved-application.json
- src/controllers/features/common/savedApplicationController.ts
- src/views/common/saved-application/saved-application.njk
- test/src/controllers/savedApplicationController.test.ts
- Updated controller and unit tests to switch yes and no options
- Updated saved application screen text
> Content update for continue saved application screen

- locales/cy/business-mustbe-aml-registered.json
- locales/en/business-mustbe-aml-registered.json
Changing business text to company as per prototype
> IDVA5-924-Content Change

- locales/cy/cannot-submit-another-application.json
- locales/en/cannot-submit-another-application.json
- src/config/index.ts
- src/controllers/features/common/cannotSubmitAnotherApplicationController.ts
- src/controllers/features/common/checkSavedApplicationController.ts
- src/controllers/index.ts
- src/routes/index.ts
- src/types/pageURL.ts
- src/views/common/cannot-submit-another-application/cannot-submit-another-application.njk
- test/src/controllers/common/cannotSubmitAnotherApplicationController.test.ts
- test/src/controllers/common/checkSavedApplicationController.test.ts
- Added kickout screen
- Added unit tests for screen
> Added kickout screen for you have already submitted an application

- src/controllers/features/common/amlBodyMembershipNumberController.ts
- src/controllers/features/limited/selectAmlSupervisorController.ts
- src/controllers/features/unincorporated/selectAmlSupervisorController.ts
- src/views/common/aml-body-number/aml-body-number.njk
- src/views/common/select-aml-supervisory-bodies/select-aml-supervisory-bodies.njk
- updated display of h1 for AML pages
> Idva5 940 display name above <h1> aml screens

- src/controllers/features/common/checkYourAnswers.ts
- src/services/transactions/transaction_service.ts
- test/src/services/transaction/transaction_service.test.ts
> Revert sending company name and number with transaction

- package-lock.json
- package.json
Updating chs-node-utils to get the latest changes which  Capture analytics for the English AND Welsh toggle
> IDVA5-1075-Updating chs-node-utils 

- package-lock.json
- package.json
- src/controllers/features/limited/isThisYourCompanyController.ts
- src/services/checkYourAnswersService.ts
- src/services/company-details/companyDetailsService.ts
- test/src/services/checkYourAnswersService.test.ts
Updating company details to only store company name and company number
> Updating the data saved in database

- package-lock.json
- package.json
- src/controllers/features/limited/addressCorrespondanceSelectorController.ts
- src/controllers/features/limited/correspondenceAddressAutoLookupController.ts
- src/controllers/features/limited/correspondenceAddressListController.ts
- src/controllers/features/limited/isThisYourCompanyController.ts
- src/controllers/features/sole-trader/correspodanceAddressDetailsController.ts
- src/controllers/features/sole-trader/correspondenceAddressAutoLookupController.ts
- src/controllers/features/unincorporated/addressCorrespondanceSelectorController.ts
- src/controllers/features/unincorporated/businessAddressAutoLookupController.ts
- src/controllers/features/unincorporated/correspondenceAddressAutoLookupController.ts
- src/controllers/features/unincorporated/correspondenceAddressListController.ts
- src/services/address/addressLookUp.ts
- src/services/business-address/businessAddressService.ts
- src/services/checkYourAnswersService.ts
- src/services/correspondence-address/correspondence-address-manual.ts
- src/views/common/correspondence-address-confirm/correspondence-address-confirm.njk
- src/views/features/unincorporated/confirm-your-business-address/confirm-your-business-address.njk
- test/mocks/address.mock.ts
- test/src/controllers/limited/addressCorrespondanceSelectorController.test.ts
- test/src/controllers/limited/correspondenceAddressConfirmController.test.ts
- test/src/controllers/limited/correspondenceAddressLookUp.test.ts
- test/src/controllers/soleTrader/correspondenceAddressAutoLookupController.test.ts
- test/src/controllers/soleTrader/correspondenceAddressConfirmController.test.ts
- test/src/controllers/unincorporated/correspondenceAddressConfirmController.test.ts
- test/src/services/correspondence-address/correspondence-address-manual.test.ts
updated address fields to use new address format in api-sdk-node
> Updated all address fields to use new address format

- package-lock.json
- package.json
- src/controllers/features/common/applicationConfirmationController.ts
- src/controllers/features/limited/addressCorrespondanceSelectorController.ts
- src/controllers/features/limited/isThisYourCompanyController.ts
- src/controllers/features/limited/sectorYouWorkInController.ts
- src/controllers/features/unincorporated/addressCorrespondanceSelectorController.ts
- src/controllers/features/unincorporated/businessAddressAutoLookupController.ts
- src/controllers/features/unincorporated/unincorporatedConfirmYourBusinessAddressController.ts
- src/model/ACSPData.ts
- src/services/acspDataService.ts
- src/services/address/addressLookUp.ts
- src/services/business-address/businessAddressService.ts
- src/services/checkYourAnswersService.ts
- test/src/controllers/common/applicationConfirmationController.test.ts
- test/src/controllers/limited/addressCorrespondanceSelectorController.test.ts
- test/src/services/address/addressLookup.test.ts
- test/src/services/checkYourAnswersService.test.ts
changes to remove email from updating to db, 
renaming businessAddress to registeredOfficeAddress
> Idva5 1141 tech debt

- src/middleware/session_middleware.ts
- src/views/partials/__footer.njk
- src/views/partials/piwik.njk
- moved template div from header to footer to fix errors not being shown in Matomo
> Fixing errors

- package-lock.json
- package.json
- src/services/acspRegistrationService.ts
Changing the path patterns to call acsp-api
> Changing the path patterns to call acsp-api

- src/middleware/authentication_middleware.ts
- test/src/middleware/authentication_middleware.test.ts
-update using authmiddleware instead of acspAuthMiddleware
-update test
> using authmiddleware instead of acspAuthMiddleware

- src/middleware/company_authentication_middleware.ts
- test/src/middleware/company_authentication_middleware.test.ts
Using new auth middleware for Auth code page
> Acsp auth middleware Auth code page 

- src/middleware/company_authentication_middleware.ts
- test/src/middleware/company_authentication_middleware.test.ts
Reverting the fix to see if auth code screen comes back
> Reverting Acsp auth middleware fix

- package-lock.json
> Fixing vulnerabilities

- src/controllers/features/limited/addressCorrespondanceSelectorController.ts
- test/src/controllers/limited/addressCorrespondanceSelectorController.test.ts
Adding undefined check for correspondence address.
> Adding undefined check for correspondence address.

- test/src/controllers/limited/whichSectorOtherController.test.ts
> Fixing faling unit test

- locales/cy/check-your-answers.json
- locales/en/check-your-answers.json
- src/controllers/features/limited/whatIsYourEmailAddressController.ts
- src/controllers/features/sole-trader/whatIsYourEmailAddressController.ts
- src/controllers/features/unincorporated/addressCorrespondanceSelectorController.ts
- src/controllers/features/unincorporated/whatIsYourEmailAddressController.ts
- src/model/Answers.ts
- src/services/checkYourAnswersService.ts
- src/views/partials/check-your-answers/limited-answers.njk
- src/views/partials/check-your-answers/sole-trader-answers.njk
- src/views/partials/check-your-answers/unincorporated-answers.njk
- test/mocks/check_your_answers.mock.ts
- test/src/controllers/unincorporated/addressCorrespondanceSelectorController.test.ts
- test/src/services/checkYourAnswersService.test.ts
Fixed bug where a different email is pre selected
fixed unincorporated routing issue
> Added email to check your answers screen

- src/controllers/features/unincorporated/addressCorrespondanceSelectorController.ts
- test/src/controllers/limited/addressCorrespondanceSelectorController.test.ts
- test/src/controllers/unincorporated/addressCorrespondanceSelectorController.test.ts
Fixing default address selection in Unincorporated journey
> Fixing default address selection in Unincorporated journey

- src/controllers/features/limited/addressCorrespondanceSelectorController.ts
- src/controllers/features/unincorporated/addressCorrespondanceSelectorController.ts
setting correspondenceAddressIsSameAsRegisteredOfficeAddress as true when address in same
> setting correspondenceAddressIsSameAsRegisteredOfficeAddress as true

- locales/cy/check-your-answers.json
- locales/en/check-your-answers.json
- src/services/checkSavedApplicationService.ts
- src/views/common/check-your-answers/check-your-answers.njk
- src/views/common/other-type-of-business/other-type-of-business.njk
Added inset text to check your answers page
Flipped order of other type of business radio buttons Fixed linting errors
> Small content update

- src/controllers/features/common/typeOfBusinessController.ts
- test/src/controllers/common/typeOfBusinessController.test.ts
Moved transaction post request to type of business post request, to prevent transaction being created if user does not start an application
> Moved creation of transaction to post request in type of business screen

- locales/cy/already-part-of-an-acsp.json
- locales/en/already-part-of-an-acsp.json
- src/views/common/cannot-register-again/cannot-register-again.njk
- test/src/controllers/common/cannotRegisterAgainController.test.ts
Adding content for approved stop screen and matomo analytics
IDVA5-1320
> Adding content for approved stop screen and matomo analytics

- locales/cy/aml-body-number.json
- locales/en/aml-body-number.json
- src/validation/amlBodyMembershipNumber.ts
- test/src/controllers/common/amlBodyMembershipNumberController.test.ts
- Updated the AML membership number to not allow a number greater than 256 characters long
> Added length validation for AML membership number

- src/controllers/features/common/typeOfBusinessController.ts
- src/controllers/features/limited/businessMustbeAmlRegisteredController.ts
- src/services/url.ts
- test/mocks/transaction_mock.ts
- test/src/controllers/common/typeOfBusinessController.test.ts
Issues on clicking browser back AML stop screen for Limited journey
> IDVA5-1277

- src/views/common/your-responsibilities/your-responsibilities.njk
Fixed accessibility issue on your responsibilities page regarding nested lists.
Moved nested list inside of the <li> tag
> Fixed accessibility issue on your responsibilities page

- src/controllers/features/common/otherTypeOfBusinessController.ts
- src/controllers/features/common/typeOfBusinessController.ts
- src/services/acspDataService.ts
- src/services/acspRegistrationService.ts
- src/services/typeOfBusinessService.ts
- test/src/controllers/common/otherTypeOfBusinessController.test.ts
- test/src/controllers/common/typeOfBusinessController.test.ts
- test/src/controllers/limited/correspondenceAddressConfirmController.test.ts
- test/src/controllers/limited/isThisYourCompanyController.test.ts
- test/src/controllers/limited/whatIsYourRoleController.test.ts
- test/src/controllers/soleTrader/correspondenceAddressConfirmController.test.ts
- test/src/controllers/soleTrader/whatIsYourRoleController.test.ts
- test/src/controllers/unincorporated/correspondenceAddressConfirmController.test.ts
- test/src/services/acspDataService.test.ts
- test/src/services/typeOfBusinessService.test.ts
- Started new transaction when user changes type of business
- Deleted old transaction and application when the user changes type of business
- Moved the creation of the transaction to post
> Started new transaction when user changes type of business

- locales/cy/address-look-up.json
- locales/en/address-look-up.json
- src/services/correspondence-address/correspondence-address-manual.ts
- src/views/common/correspondence-address-manual/capture-correspondence-address-manual.njk
- src/views/features/unincorporated/business-address-auto-lookup/auto-lookup-address.njk
- src/views/partials/country-typeahead-input.njk
- test/src/services/correspondence-address/correspondence-address-manual.test.ts
Fixed wrong hint text showing on business address lookup screen
> Fixed country name and premise not being retained on error

- terraform/groups/ecs-service/locals.tf
Adding the update acsp details endpoint to lb_listener_path to test access to new service on cidev
> Adding update acsp service endpoint to lb path

- src/config/index.ts
- src/utils/properties.ts
Removed duplicate piwik env properties and organised env variables
> Updating environment variables

- src/controllers/features/common/checkYourAnswers.ts
- src/controllers/features/common/otherTypeOfBusinessController.ts
- src/controllers/features/common/typeOfBusinessController.ts
- src/controllers/indexController.ts
- src/utils/properties.ts
- src/views/common/check-your-answers/check-your-answers.njk
- src/views/common/index/home.njk
- src/views/common/other-type-of-business/other-type-of-business.njk
- src/views/common/type-of-business/type-of-business.njk
Added env variables for Matomo goals
> IDVA5-1574 Updating Matomo goal id to select from env variables

- package-lock.json
- package.json
- src/app.ts
- src/common/__utils/session.ts
- src/middleware/update_acsp_authentication_middleware.ts
- test/mocks/all_middleware_mock.ts
- test/mocks/session.mock.ts
- test/mocks/update_acsp_authentication_middleware_mock.ts
- test/src/common/__util/session.test.ts
- test/src/middleware/update_acsp_authentication_middleware.test.ts
Added authentication middleware for update ACSP service to allow only the ACSP owner to access the service
> Added authentication middleware for update acsp service

- test/src/controllers/limited/addressCorrespondanceSelectorController.test.ts
- test/src/controllers/unincorporated/businessAddressManualEntryController.test.ts
- test/src/controllers/updateAcspDetails/indexController.test.ts
- test/src/controllers/updateAcspDetails/whatIsYourNameController.test.ts
- test/src/controllers/updateAcspDetails/whereDoYouLiveController.test.ts
updated tests for update-acsp flags
> updated tests for update-acsp flags

- src/app.ts
- src/views/common/check-your-answers/check-your-answers.njk
- src/views/common/index/home.njk
- src/views/common/other-type-of-business/other-type-of-business.njk
- src/views/common/type-of-business/type-of-business.njk
- src/views/partials/__styles.njk
- src/views/partials/business_name.njk
- src/views/partials/piwik.njk
- src/views/partials/user_name.njk
Removing inline style items and replacing them with classes
Moved the styling to styles.njk
Removing inline script from button attributes and replaced them with event listeners inside the script tags
> Fixing console errors from CSP

- src/middleware/content_security_policy_middleware_config.ts
Fixing issue when clicking the Start Now button from the landing page when user is already logged in
> Fixing issue when clicking the Start Now button from the landing page when user is already logged in

- src/middleware/content_security_policy_middleware_config.ts
Updating form-action to include chs url
> Updating form-action to include chs url

- src/controllers/features/common/cannotRegisterAgainController.ts
- src/types/pageURL.ts
- src/views/common/application-confirmation/application-confirmation.njk
- src/views/common/cannot-register-again/cannot-register-again.njk
https://companieshouse.atlassian.net/browse/IDVA5-1651
- Added authorised agent link to stop screen
- Added correct variable for feedbackLink on confirmation screen
> IDVA5-1651 Registration links updated

- src/middleware/content_security_policy_middleware_config.ts
Adding Account URL and oauth2 callback url
> Adding Account URL and oauth2 callback url

- src/views/common/correspondence-address-manual/capture-correspondence-address-manual.njk
Allowing country input to retain on page load
> Allowing country input to retain on page load

- src/controllers/features/update-acsp/indexController.ts
- src/views/features/update-acsp-details/index/home.njk
Adding business name to the landing page
> Adding business name to the landing page

- src/controllers/indexController.ts
- src/utils/properties.ts
- src/views/common/index/home.njk
Updating text on landing page to include the fee
> Adding fee to landing page

- src/model/AMLSupervisoryBodies.ts
Updating General Council of the Bar to Bar Standards Board (BSB)
> Updating AML body name 

- src/middleware/content_security_policy_middleware_config.ts
Adding all URLs in the redirect chain to CSP
> Adding all URLs in the redirect chain to CSP

- src/middleware/content_security_policy_middleware_config.ts
adding CHS url in connect src as well
> adding CHS url in connect src as well

- .dockerignore
- Dockerfile
Adding node_modules to the copy list in dockerfile when creating the image.
Mind you this will increase the size of the local image. My image currently is 680MB.
> Adding node_modules to the copy list in dockerfile

- src/app.ts
changing csrfProtection to be enabled on all pages
> changing csrfProtection to be enabled on all pages

- src/app.ts
- src/middleware/content_security_policy_middleware_config.ts
> Reverting back csrf changes

- src/middleware/content_security_policy_middleware_config.ts
setting upgradeInsecureRequests to false
> setting upgradeInsecureRequests to false

- src/middleware/content_security_policy_middleware_config.ts
> Adding identity values in CSP

- src/middleware/content_security_policy_middleware_config.ts
Changing form action to include all account and all chs urls
> Changing form action

- src/middleware/content_security_policy_middleware_config.ts
Removing https from url in csp
> Removing https from url in csp

- locales/cy/common-errors.json
- locales/cy/common.json
- locales/cy/error-pages.json
- locales/cy/start-page.json
Adding missing Welsh translations
> Adding missing Welsh translations

- locales/cy/name-registered-with-aml.json
Updating missing Welsh translation for Name registered with AML screen
> Updating missing welsh translation

- src/validation/commonAddressManual.ts
- test/src/validation/commonAddressManual.test.ts
fix address county validation to accept hyphen and apostrophes
> IDVA5-1755 fix address county validation

- src/views/common/what-is-your-role/what-is-your-role.njk
- src/views/features/limited/name-registered-with-aml/name-registered-with-aml.njk
- src/views/partials/piwik.njk
- removed unused snippets implemented keeping in mind about the future requirements. i.e. boolean variables and regular expressions for partial obliteration.
> IDVA5-1621 ACSP Registration - Updates to Matomo Analytics Implementation fix-1

- src/middleware/content_security_policy_middleware_config.ts
> adding all urls to CSP

- package-lock.json
- src/middleware/authentication_middleware.ts
If user is signed in then just do the next function
> If user is signed in then just do the next function

- locales/cy/common.json
- locales/en/common.json
- src/views/partials/nav/top.njk
Removing navbar link: 'Companies House does not verify the accuracy of the information filed'
> Removing ch does not verify navbar link

- package-lock.json
- src/middleware/authentication_middleware.ts
Reverts companieshouse/acsp-web
> Revert If user is signed in then just do the next function

- src/views/partials/nav/top.njk
> Adding padding to navbar

- src/app.ts
- src/middleware/content_security_policy_middleware_config.ts
removing the CSP for the start now page.
> removing the CSP for the start now page.

- package-lock.json
- src/app.ts
- src/middleware/content_security_policy_middleware_config.ts
Allowing all form actions on the home page
> Allowing all form actions on the home page

- src/middleware/content_security_policy_middleware_config.ts
Allowing all form actions to anything within ch infrastructure
> Allowing all form actions to anything within ch infrastructure

- src/middleware/content_security_policy_middleware_config.ts
- src/services/business-address/businessAddressService.ts
Alloweing all urls on the start page
> Allowing all urls on the start page

- locales/cy/update-acsp-details-application-submitted.json
- locales/en/update-acsp-details-application-submitted.json
- src/common/__utils/sessionHelper.ts
- src/config/index.ts
- src/controllers/features/update-acsp/applicationConfirmationController.ts
- src/controllers/features/update-acsp/updateYourDetailsController.ts
- src/controllers/index.ts
- src/routes/updateAcsp.ts
- src/types/pageURL.ts
- src/views/features/update-acsp-details/application-confirmation/application-confirmation.njk
- src/views/features/update-acsp-details/update-your-details.njk
- test/src/controllers/updateAcspDetails/applicationConfirmationController.test.ts
- test/src/controllers/updateAcspDetails/cancelAnUpdateController.test.ts
- test/src/controllers/updateAcspDetails/updateYourDetailsController.test.ts
Work completed for ticket:
[IDVA5-1458](https://companieshouse.atlassian.net/browse/IDVA5-1458?atlOrigin=eyJpIjoiN2I2YjYyMTY0ODNjNDg3MDgyNmMxYjhjY2Y2ODk3MzciLCJwIjoiaiJ9)
- Created application submitted njk file and locales text files for new screen.
- Created controller with GET for new screen.
- Updated deleteAllSessionData util method to delete all stored session data.
- Added routing to new screen.
- Included partials/csrf_token.njk within the form of update-acsp-details.njk file
- Add unit tests.
[IDVA5-1458]: https://companieshouse.atlassian.net/browse/IDVA5-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding application complete to update acsp service

- locales/cy/add-aml-supervisor.json
- locales/en/add-aml-supervisor.json
- src/common/__utils/constants.ts
- src/config/index.ts
- src/controllers/features/update-acsp/addAmlSupervisorController.ts
- src/controllers/features/update-acsp/updateYourDetailsController.ts
- src/controllers/index.ts
- src/routes/updateAcsp.ts
- src/types/pageURL.ts
- src/validation/addAmlSupervisor.ts
- src/views/features/update-acsp-details/add-aml-supervisory-body/add-aml-supervisory-body.njk
- src/views/features/update-acsp-details/update-your-details.njk
- test/src/controllers/updateAcspDetails/addAmlSupervisorController.test.ts
Added new page to allow user to add a new AML body
> Added new page to allow user to add a new AML body

- src/views/common/application-confirmation/application-confirmation.njk
- src/views/common/index/home.njk
- src/views/common/stop-not-relevant-officer/stop-not-relevant-officer.njk
Adding the urls for the following pages:
1. Start Page
2. Kickout page
3. Confirmation Page
> IDVA5-1293 Add guidance links to service

- src/views/partials/update-your-details/limited-answers.njk
https://companieshouse.atlassian.net/browse/IDVA5-1461
Tag was missing after updating registered office address details. Now showing as below:
> Details updated tag added for registered office address

- src/services/update-acsp/amlSupervisorService.ts
- src/views/features/update-acsp-details/update-your-details.njk
- test/src/services/update_acsp/amlSupervisorService.test.ts
The removal of the newly added aml
> IDVA5-1707 Remove an AML body -- removal of the newly added AML

- src/app.ts
Updating CSP to have * form action for type of business page only if verify sole trader only feature flag is true
> Updating CSP to have * form action for type of business page only if verify sole trader only feature flag is true

- locales/cy/cancel-all-updates.json
- locales/en/cancel-all-updates.json
- test/src/controllers/updateAcspDetails/cancelAllUpdatesController.test.ts
https://companieshouse.atlassian.net/browse/IDVA5-1713
Some content changes to match the prototype
> IDVA5-1713 Content update to match prototype

- src/controllers/features/update-acsp/businessAddressManualController.ts
- src/services/business-address/businessAddressService.ts
- test/src/services/business-address/business-address-manual.test.ts
For update business address manual screen, the country value from DB is fetched in the format "NORTHERN IRELAND". As part of the change, this value is converted to format "Northern Ireland"
> fix country field for business address

- src/services/business-address/businessAddressService.ts
- src/views/features/update-acsp-details/application-confirmation/application-confirmation.njk
Adding top margin spacing to application submitted screen for update acsp details
> Adding margin to application submitted panel

- src/controllers/features/update-acsp/cancelAllUpdatesController.ts
- src/types/pageURL.ts
- test/src/controllers/updateAcspDetails/cancelAllUpdatesController.test.ts
https://companieshouse.atlassian.net/browse/IDVA5-1713
Request to redirect to authorised agent link rather than manage users so have replaced that and remove the url for manage users which is no longer used.
> IDVA5-1713 Replacing manage users link with authorised agent link

- src/controllers/features/update-acsp/cancelAllUpdatesController.ts
- test/src/controllers/updateAcspDetails/cancelAllUpdatesController.test.ts
https://companieshouse.atlassian.net/browse/IDVA5-1713
Removing variable assigned to url
> Removing variable assigned to url

- src/controllers/features/update-acsp/applicationConfirmationController.ts
- src/controllers/features/update-acsp/businessAddressAutoLookupController.ts
- src/controllers/features/update-acsp/cancelAllUpdatesController.ts
- src/controllers/features/update-acsp/cancelAnUpdateController.ts
- src/controllers/features/update-acsp/indexController.ts
- src/controllers/features/update-acsp/provideAmlDetailsController.ts
- src/controllers/features/update-acsp/removeAmlSupervisorController.ts
- src/controllers/features/update-acsp/whatIsTheBusinessNameController.ts
- src/controllers/features/update-acsp/whatIsYourNameController.ts
- src/controllers/features/update-acsp/whereDoYouLiveController.ts
- test/src/controllers/updateAcspDetails/businessAddressAutoLookupController.test.ts
- test/src/controllers/updateAcspDetails/businessAddressManualController.test.ts
- test/src/controllers/updateAcspDetails/cancelAllUpdatesController.test.ts
- test/src/controllers/updateAcspDetails/cancelAnUpdateController.test.ts
- test/src/controllers/updateAcspDetails/indexController.test.ts
- test/src/controllers/updateAcspDetails/provideAmlDetailsController.test.ts
- test/src/controllers/updateAcspDetails/removeAmlSupervisorController.test.ts
- test/src/controllers/updateAcspDetails/updateYourDetailsController.test.ts
- test/src/controllers/updateAcspDetails/whatIsTheBusinessNameController.test.ts
- test/src/controllers/updateAcspDetails/whatIsYourNameController.test.ts
- test/src/controllers/updateAcspDetails/whereDoYouLiveController.test.ts
https://companieshouse.atlassian.net/browse/IDVA5-1890
Added a try-catch block to all the controllers. This will prevent the service crashing if an error occurs as all of the errors will be caught and handled correctly.
> Adding try-catch blocks to all controllers

- src/middleware/registration_variables_middleware.ts
- src/views/layouts/default.njk
- src/views/partials/nav/navbar.njk
- src/views/partials/nav/signout-bar.njk
- src/views/partials/nav/top.njk
Updating nav bar for registration journey
Added an if check to switch nav bar for registration/update
> Updating nav bar for registration journey

- src/controllers/features/update-acsp/yourUpdatesController.ts
- src/views/features/update-acsp-details/your-updates/your-updates.njk
Fixed missing language query on where do you live edit link
Fixed if statement for canceling sole trader address.
Updated the post controller if statement to match the get request for youUpdatesController
> Bug fixes for IDVA5-1840

- locales/cy/your-updates.json
- locales/en/your-updates.json
- src/app.ts
- test/src/controllers/updateAcspDetails/yourUpdatesController.test.ts
New error message for when the user clicks continue without selecting an option on the radio buttons.
Also updating the url in the CSP for the sign out page for ticket 
https://companieshouse.atlassian.net/browse/IDVA5-1833
> Updating error message for you-updates screen when no radio is selected

- src/views/common/accessibility-statement/accessibility-statement.njk
- test/src/controllers/common/accessibilityStatementController.test.ts
Changes made as part of ticket: [IDVA5-1940](https://companieshouse.atlassian.net/browse/IDVA5-1940?atlOrigin=eyJpIjoiYjg3MjhkMGI0NDk2NDg4M2FjNmVlNDlhZDE0YTNhNjAiLCJwIjoiaiJ9)
Updating content for accessibility statement page to match latest prototype
[IDVA5-1940]: https://companieshouse.atlassian.net/browse/IDVA5-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> updating accessibility page content

- src/controllers/features/common/resumeJourneyController.ts
Setting resume to true and adding application id to session when user comes back from filings page
> Setting resume to true and adding application id to session when user comes back from filings page

- src/middleware/common_variables_middleware.ts
- src/views/layouts/default.njk
Updating page language from hard coded en to dynamically switch when the language is changed
> Updating page language from hard coded en to dynamically switch when the language is changed

- locales/cy/select-aml-supervisor.json
- locales/en/select-aml-supervisor.json
- src/views/common/aml-body-number/aml-body-number.njk
- src/views/common/check-aml-details/check-aml-details.njk
- src/views/common/check-your-answers/check-your-answers.njk
- src/views/common/select-aml-supervisory-bodies/select-aml-supervisory-bodies.njk
- Welsh local Added and Updated For AML Supervisory, Check your Aml Details, AML Membership number  pages
> IDVA5-1801-Welsh Translation for AML Supervisory Bodies Pages 

- src/controllers/features/common/resumeJourneyController.ts
Revert "Setting resume to true and adding application id to session when user comes back from filings page"
This reverts commit 097232a9a663474b82fe65efceb8925e44d45bdc.
> Revert "Setting resume to true and adding application id to session when user comes back from filings page"

- locales/cy/select-aml-supervisor.json
- locales/en/select-aml-supervisor.json
- src/views/common/aml-body-number/aml-body-number.njk
- src/views/common/check-aml-details/check-aml-details.njk
- src/views/common/check-your-answers/check-your-answers.njk
- src/views/common/select-aml-supervisory-bodies/select-aml-supervisory-bodies.njk
Reverts companieshouse/acsp-web
> Revert IDVA5-1801-Welsh Translation for AML Supervisory Bodies Pages 

- src/controllers/accessibilityStatementController.ts
- src/views/common/accessibility-statement/accessibility-statement.njk
Adding language information into accessibility statement controller for cookies banner
Removing the language toggle from the accessibility statement page
> Adding language information into accessibility statement controller for cookies banner

- src/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
https://companieshouse.atlassian.net/browse/IDVA5-1896
Use hint text as the label for the countryInput form field
> Label added for countryInput form field - DAC change

- package-lock.json
- package.json
- src/controllers/features/update-acsp/yourUpdatesController.ts
- src/services/update-acsp/acspUpdateService.ts
- test/src/controllers/updateAcspDetails/yourUpdatesController.test.ts
- test/src/services/update_acsp/acspUpdateService.test.ts
- test/src/services/update_acsp/yourUpdatesService.test.ts
Saving only the updated fields to MongoDB after the transaction has been created
Checking each field to see if an update has been made if not then passing over it. If there has been a change it is added to the acspData object which is then sent to Mongo.
> Saving updated information into MongoDB.

- src/views/common/application-confirmation/application-confirmation.njk
Small update based on test feedback from testing
Ticket [IDVA5-1909](https://companieshouse.atlassian.net/browse/IDVA5-1909) 
Fixing duplicate opens in new tab text and adding brackets around that text
[IDVA5-1909]: https://companieshouse.atlassian.net/browse/IDVA5-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixing duplicate opens in new tab text and adding brackets around it

- src/views/common/check-your-answers/check-your-answers.njk
Updating hidden text to use the full AML body name rather than its abbreviation
> Updating hidden text to use the full AML body name rather than its abbreviation

- src/controllers/features/update-acsp/whatIsTheBusinessNameController.ts
- src/controllers/features/update-acsp/whereDoYouLiveController.ts
Updating what is the business name and where do you live to show the updated address when the user goes back to that screen
> Updating what is the business name and where do you live to show the updated address when the user goes back to that screen

- src/controllers/features/update-acsp/whatIsYourEmailAddressController.ts
- test/src/controllers/updateAcspDetails/whatIsYourEmailAddressController.test.ts
Ticket [IDVA5-1971](https://companieshouse.atlassian.net/browse/IDVA5-1971)
Updating the routing on email address screen to take use to check updates screen if they make an update or to view and update screen if they do not.
[IDVA5-1971]: https://companieshouse.atlassian.net/browse/IDVA5-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating the routing on email address screen

- src/controllers/features/sole-trader/whereDoYouLiveController.ts
- src/controllers/features/update-acsp/whereDoYouLiveController.ts
- src/services/where-do-you-live/whereDoYouLive.ts
- test/src/services/where-do-you-live/whereDoYouLive.test.ts
Ticket [IDVA5-1852](https://companieshouse.atlassian.net/browse/IDVA5-1852)
Updated getCountryPayload function to get the country from both AcspFullProfile and AcspData types
Fixed spelling mistake in WhereDoYouLiveBodyService service name
Refactored unit tests
[IDVA5-1852]: https://companieshouse.atlassian.net/browse/IDVA5-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updated getCountryPayload function

- src/services/where-do-you-live/whereDoYouLive.ts
- test/src/services/where-do-you-live/whereDoYouLive.test.ts
Updated where do you live function to fix capitalised country names not showing in radios
> Updated where do you live function to fix capitalised country names not showing in radios

- src/controllers/features/update-acsp/yourUpdatesController.ts
Ticket [IDVA5-1772](https://companieshouse.atlassian.net/browse/IDVA5-1772)
Calling closing transaction after data is saved to mongo
[IDVA5-1772]: https://companieshouse.atlassian.net/browse/IDVA5-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Closing transaction after data is saved to mongo

- src/validation/whereDoYouLive.ts
- test/src/controllers/updateAcspDetails/whereDoYouLiveController.test.ts
Adding case insensitive country input for where do you live screen.
This is needed because the country is sent in capitals from data sync
> Adding case insensitive country input for where do you live

- src/validation/dateOfACSPUpdateDetailsChange.ts
- test/src/validation/dateOfACSPUpdateDetailsChange.test.ts
Fixing test returned issues: validation error message and 100 years of range for the past
> Update ACSP - When did this change functionality - All Updates (except AML)

- src/controllers/features/common/checkYourAnswers.ts
- src/controllers/features/update-acsp/yourUpdatesController.ts
- src/services/transactions/transaction_service.ts
- test/src/services/transaction/transaction_service.test.ts
Ticket [IDVA5-1772](https://companieshouse.atlassian.net/browse/IDVA5-1772)
Updating the close transaction method to take the reference and description of the transaction. This is so the correct description and reference are shown on the transaction based on the journey
[IDVA5-1772]: https://companieshouse.atlassian.net/browse/IDVA5-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating the close transaction method to take the reference and description

- src/common/__utils/constants.ts
- src/controllers/features/update-acsp/dateOfTheChangeController.ts
- src/controllers/features/update-acsp/whatIsYourNameController.ts
- src/services/update-acsp/dateOfTheChangeService.ts
- test/src/services/update_acsp/dateOfTheChangeService.test.ts
fixing test returned issue of back button
> IDVA5-1969 Update ACSP - When did this change - What is your Name [Backend]-- fixing test returned isssue of back button

- src/views/features/update-acsp-details/your-updates/your-updates.njk
Adding a space between the update date and the new information
> Adding a space between the update date and the new information

- src/views/common/accessibility-statement/accessibility-statement.njk
Changes for ticket: [IDVA5-1036](https://companieshouse.atlassian.net/browse/IDVA5-1036?atlOrigin=eyJpIjoiMzkyOGI4ZjNiMjkyNDhjZDhkNGQwZmIyZDdhZjlkYmIiLCJwIjoiaiJ9)
- Updating Accessibility page content
[IDVA5-1036]: https://companieshouse.atlassian.net/browse/IDVA5-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating accessibility statement content

- src/services/address/addressLookUp.ts
- src/services/common.ts
- test/src/services/address/addressLookup.test.ts
fixing the prod issue of country returned null/empty on postcode lookups of border countries.
> IDVA5-2046 ACSP Registration - Redirect Users to Manual Address Entry Screen for ''Border'' Postcode Lookup Issue

- src/controllers/indexController.ts
- src/types/pageURL.ts
- src/views/common/index/home.njk
Request to change url to "identity-verification/verify-your-identity-for-companies-house".
> IDVA5-2042 - Update start page content

- locales/cy/what-is-your-name.json
- locales/en/what-is-your-name.json
- src/validation/whatIsYourName.ts
- test/src/controllers/updateAcspDetails/whatIsYourNameController.test.ts
Ticket [IDVA5-2048](https://companieshouse.atlassian.net/browse/IDVA5-2048)
Adding error messages to the what is your name screen when the user does not make a change to their name
[IDVA5-2048]: https://companieshouse.atlassian.net/browse/IDVA5-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating error messages on the what is your name screen

- package-lock.json
- src/views/partials/update-your-details/limited-answers.njk
- src/views/partials/update-your-details/sole-trader-answers.njk
- src/views/partials/update-your-details/unincorporated-answers.njk
Ticket [IDVA5-1986](https://companieshouse.atlassian.net/browse/IDVA5-1986)
Adding date change to the view and update screen for correspondence address
[IDVA5-1986]: https://companieshouse.atlassian.net/browse/IDVA5-1986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding date change to the view and update screen for correspondence address

- src/controllers/features/update-acsp/indexController.ts
- test/src/controllers/updateAcspDetails/indexController.test.ts
Updates in progress are cleared on visit of the index page, below changes are fixing this.
- A check is performed in the index page to find if any modification(s) in progress.
- Preventing the overwrite based on the check.
https://companieshouse.atlassian.net/browse/IDVA5-2081
> IDVA5-2081 Update ACSP-Updated information is not displaying.

- src/views/features/update-acsp-details/update-your-details.njk
Ticket [IDVA5-2094](https://companieshouse.atlassian.net/browse/IDVA5-2094)
Adding title to view and update page. All other pages have the correct title and __meta_header.njk has the correct logic
[IDVA5-2094]: https://companieshouse.atlassian.net/browse/IDVA5-2094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding title to view and update page

- locales/cy/add-aml-supervisor.json
- locales/en/add-aml-supervisor.json
- src/validation/addAmlSupervisor.ts
- test/mocks/acsp_profile.mock.ts
- test/src/controllers/updateAcspDetails/addAmlSupervisorController.test.ts
Ticket [IDVA5-2059](https://companieshouse.atlassian.net/browse/IDVA5-2059)
Adding an error message to the Select AML body screen when the user tries to add over 25 AML bodies
[IDVA5-2059]: https://companieshouse.atlassian.net/browse/IDVA5-2059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding error message for more than 25 AML bodies

- src/views/partials/nav/navbar.njk
Change required for ticket:
[IDVA5-2111](https://companieshouse.atlassian.net/browse/IDVA5-2111)
- Hiding 'Your Companies' link from navbar on Update ACSP Service as 'Your Companies' service is not yet live
[IDVA5-2111]: https://companieshouse.atlassian.net/browse/IDVA5-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hiding your companies navbar link

- locales/cy/address-look-up.json
- locales/en/address-look-up.json
- src/validation/correspondenceAddressAutoLookup.ts
- test/src/controllers/updateAcspDetails/businessAddressAutoLookupController.test.ts
Ticket [IDVA5-2055](https://companieshouse.atlassian.net/browse/IDVA5-2055)
Updating error messages for auto look business and registered office addresses
[IDVA5-2055]: https://companieshouse.atlassian.net/browse/IDVA5-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating error messages for auto look business and registered office addresses

- src/views/features/update-acsp-details/provide-aml-details/provide-aml-details.njk
Ticket [IDVA5-2061](https://companieshouse.atlassian.net/browse/IDVA5-2061)
Making new link open in a new tab
[IDVA5-2061]: https://companieshouse.atlassian.net/browse/IDVA5-2061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Making new link open in a new tab

- src/services/transactions/transaction_service.ts
- src/services/update-acsp/acspUpdateService.ts
- test/src/services/update_acsp/acspUpdateService.test.ts
Adding the company name into the transaction so it shows on the emails being sent
> Adding the company name into the transaction so it shows on the emails being sent

- src/controllers/features/update-acsp/businessAddressManualController.ts
- test/src/controllers/updateAcspDetails/businessAddressManualController.test.ts
corrected the wrong payload parameter in the businessAddressManualController
> IDVA5-2108 corrected the wrong payload parameter in the businessAddressManualController

- src/views/features/update-acsp-details/update-your-details.njk
- src/views/partials/update-your-details/limited-answers.njk
- src/views/partials/update-your-details/sole-trader-answers.njk
- src/views/partials/update-your-details/unincorporated-answers.njk
Fixing cancel button not showing up due to spelling mistake in njk file
> Fixing cancel button not showing up

- src/types/pageURL.ts
Was provided to use the following url:
identity-verification/direct/has-identity-been-verified
> IDVA5-2042-Update start page content

- locales/cy/close-acsp-start-page.json
- locales/cy/close-acsp-what-will-happen.json
- locales/en/close-acsp-what-will-happen.json
- src/config/index.ts
- src/controllers/features/close-acsp/indexController.ts
- src/controllers/features/close-acsp/whatWillHappenController.ts
- src/controllers/index.ts
- src/middleware/close-acsp/close_variables_middleware.ts
- src/routes/closeRoutesAcsp.ts
- src/types/pageURL.ts
- src/validation/whatWillHappen.ts
- src/views/features/close-acsp/index/home.njk
- src/views/features/close-acsp/what-will-happen/what-will-happen.njk
- test/src/controllers/closeAcsp/indexController.test.ts
- test/src/controllers/closeAcsp/whatWillHappenController.test.ts
Ticket [IDVA5-1504](https://companieshouse.atlassian.net/browse/IDVA5-1504)
Adding the What will happen when you close the authorised agent account screen
Updating the close ACSP start page to direct to the newly added screen and to save the data from data sync into the session
[IDVA5-1504]: https://companieshouse.atlassian.net/browse/IDVA5-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Idva5 1504 what will happen screen

- src/views/features/update-acsp-details/your-updates/your-updates.njk
Ticket [IDVA5-2164](https://companieshouse.atlassian.net/browse/IDVA5-2164)
Updating the cancel change url for business address to cancel the business address update from the your updates screen
[IDVA5-2164]: https://companieshouse.atlassian.net/browse/IDVA5-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating the cancel change url for business address

- src/controllers/features/update-acsp/businessAddressConfirmController.ts
- src/controllers/features/update-acsp/correspondenceAddressConfirmController.ts
- test/src/controllers/updateAcspDetails/businessAddressConfirmController.test.ts
- test/src/controllers/updateAcspDetails/correspondenceAddressConfirmController.test.ts
Ticket [IDVA5-2167](https://companieshouse.atlassian.net/browse/IDVA5-2167)
Updating confirm address screen to show the updated address on back button
[IDVA5-2167]: https://companieshouse.atlassian.net/browse/IDVA5-2167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating confirm address screen to show the updated address on back button

- locales/cy/address-look-up.json
- locales/en/address-look-up.json
- src/controllers/features/update-acsp/businessAddressListController.ts
- src/views/features/unincorporated/business-address-auto-lookup/business-address-list.njk
- test/src/controllers/updateAcspDetails/businessAddressListController.test.ts
Ticket [IDVA5-1709](https://companieshouse.atlassian.net/browse/IDVA5-1709)
Fixing missing and misspelt Welsh translations
[IDVA5-1709]: https://companieshouse.atlassian.net/browse/IDVA5-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixing missing and misspelt Welsh translations

- src/views/layouts/default.njk
- src/views/partials/__header.njk
- src/views/partials/nav/back_link.njk
- src/views/partials/phase_banner.njk
Ticket [IDVA5-2174](https://companieshouse.atlassian.net/browse/IDVA5-2174)
Adding landmarks for the back button and phase banner
[IDVA5-2174]: https://companieshouse.atlassian.net/browse/IDVA5-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Accessibility updates for back link and phase banner

- locales/cy/update-your-details.json
- locales/en/update-your-details.json
- src/views/features/update-acsp-details/update-your-details.njk
Changes for ticket:
[IDVA5-2177](https://companieshouse.atlassian.net/browse/IDVA5-2177?atlOrigin=eyJpIjoiYTM2YzM4YWJlYTE5NDkxODkzN2EyYWNlNWE5YTAzZDgiLCJwIjoiaiJ9)
Updating title and tab title text for Update ACSP Details main screen
[IDVA5-2177]: https://companieshouse.atlassian.net/browse/IDVA5-2177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating title text for Update acsp main page

- src/types/pageURL.ts
- src/views/features/update-acsp-details/your-updates/your-updates.njk
- src/views/partials/update-your-details/limited-answers.njk
- src/views/partials/update-your-details/sole-trader-answers.njk
- src/views/partials/update-your-details/unincorporated-answers.njk
- terraform/groups/ecs-service/locals.tf
Ticket [IDVA5-2162](https://companieshouse.atlassian.net/browse/IDVA5-2162)
Updating the page urls to match the ones given by UCD
[IDVA5-2162]: https://companieshouse.atlassian.net/browse/IDVA5-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating page urls for update acsp

- nodemon.json
- package-lock.json
- package.json
- src/bin/nodemon-entry.ts
Adding updates to work with new dev mode
> Adding updates to work with new dev mode

- src/controllers/features/close-acsp/confirmYouWantToCloseController.ts
- src/controllers/features/close-acsp/confirmationAuthorisedAgentClosedController.ts
- src/controllers/features/close-acsp/indexController.ts
- src/controllers/features/close-acsp/whatWillHappenController.ts
- src/middleware/close-acsp/close_variables_middleware.ts
Ticket [IDVA5-2171](https://companieshouse.atlassian.net/browse/IDVA5-2171)
Updating business name to remove ACSP from the end
Refactoring business name to be in close variables middleware
[IDVA5-2171]: https://companieshouse.atlassian.net/browse/IDVA5-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating business name to remove ACSP from the end

- src/services/update-acsp/dateOfTheChangeService.ts
- test/src/services/update_acsp/dateOfTheChangeService.test.ts
Reverting PR changes for [PR 845](https://github.com/companieshouse/acsp-web/pull/845)
> Reverting pr changes

- src/controllers/features/close-acsp/confirmYouWantToCloseController.ts
calling the close transaction method with the respective parameters
> IDVA5-1791 Close ACSP - Close a Transaction When User submit a Record (ACSP Web)

- locales/cy/close-acsp-start-page.json
- locales/en/close-acsp-start-page.json
- src/controllers/features/close-acsp/indexController.ts
- src/types/pageURL.ts
- src/views/features/close-acsp/index/home.njk
Ticket [IDVA5-2189](https://companieshouse.atlassian.net/browse/IDVA5-2189)
Updating text on the start screen of Close ACSP
Adding link to manage users dashboard
[IDVA5-2189]: https://companieshouse.atlassian.net/browse/IDVA5-2189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Close ACSP start screen content change

- src/controllers/features/update-acsp/applicationConfirmationController.ts
-- fixing the incorrect syntax of adding language
> IDVA5-2184 Update ACSP - Welsh toggle is not holding up to Authorised agent dashboard when clicking on Cancel All Updates button 

- locales/cy/common.json
- locales/en/common.json
Fix for:
[IDVA5-2258](https://companieshouse.atlassian.net/browse/IDVA5-2258)
- Updating common tab title for Close ACSP service
[IDVA5-2258]: https://companieshouse.atlassian.net/browse/IDVA5-2258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating common tab title

- package-lock.json
- package.json
- src/views/partials/__header.njk
https://companieshouse.atlassian.net/browse/IDVA5-2233?atlOrigin=eyJpIjoiYTVhYTQ0MzgwM2FlNGE1ZmIxZjY4NzQ0MTQzOGM5MTUiLCJwIjoiaiJ9
Update Queen Elizabeth II's St. Edward's Crown logo to King Charles III's Tudor Crown.
> Use Tudor Crown logo in the top banner

- src/views/layouts/default.njk
- src/views/partials/nav/back_link.njk
Ticket: https://companieshouse.atlassian.net/browse/IDVA5-2307?atlOrigin=eyJpIjoiMjRkNWJmYjc3NDNmNDFjNTlmYzYxZGRhZjJhMzE0MjYiLCJwIjoiaiJ9
Aligned navigation banner
> Realign navigation banner element

- package-lock.json
- src/services/checkSavedApplicationService.ts
- test/mocks/company_profile_mock.ts
- test/src/services/checkSavedApplicationService.test.ts
- test/src/services/companyDetailsService.test.ts
Reverts companieshouse/acsp-web#887
> Revert IDVA5-2197 Register an ACSP - Allow Previously Closed/ Ceased ACSPs to Access Registration Service

- src/validation/soleTraderWhatIsTheBusinessName.ts
- src/validation/unicorporatedWhatIsTheBusinessName.ts
- test/src/controllers/soleTrader/whatIsTheBusinessName.test.ts
- test/src/controllers/unincorporated/whatIsTheBusinessNameController.test.ts
-Modified the reg ex to include the +
-Added tests to confirm + in the business name is accepted.
https://companieshouse.atlassian.net/browse/IDVA5-2375
> IDVA5-2375 Live Issue: ACSP registration application rejected due to 'and' instead of '+' not being accepted -modified the reg ex to include the +

- locales/cy/stop-not-account-owner.json
Changes for ticket: 
[IDVA5-2355](https://companieshouse.atlassian.net/browse/IDVA5-2355?atlOrigin=eyJpIjoiNWI0MDE3MGZmODI2NDJmNmFkNjIzMmFhYWJiMmU5MTAiLCJwIjoiaiJ9)
- Adding Welsh language content to stop not account owner screen
[IDVA5-2355]: https://companieshouse.atlassian.net/browse/IDVA5-2355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating Welsh text for non owner stop screen

- src/services/checkSavedApplicationService.ts
- test/src/services/checkSavedApplicationService.test.ts
IDVA5-2397 Register an ACSP - Allow Previously Registered ACSP Member to Register a New ACSP - adding the null transaction check
> IDVA5-2397 Register an ACSP - Allow Previously Registered ACSP Member to Register a New ACSP

- src/services/checkSavedApplicationService.ts
- added condition to stop the application submission when a new user is added.
>  IDVA5-2397 Register an ACSP - Allow Previously Registered ACSP Member to Register a New ACSP

- sonar-project.properties
**Jira Ticket**
https://companieshouse.atlassian.net/browse/IDVA5-2423
**Documentation**
https://companieshouse.atlassian.net/wiki/spaces/DEVOPS/pages/4927324161/Sonarqube+Configuration+and+Migration
> IDVA5-2423: Upgrade Sonarqube

- src/middleware/content_security_policy_middleware_config.ts
Adding "https://*.company-information.service.gov.uk" to test is CSP issue is resolved
> Adding https://*.company-information.service.gov.uk to formActionDirective for testing

- src/views/partials/__header.njk
https://companieshouse.atlassian.net/browse/IDVA5-2454?atlOrigin=eyJpIjoiZGM1YWZiMjAyY2QzNGVhYTgxMjYxODA1M2U5ZjZhYzciLCJwIjoiaiJ9
- Updated header.njk to allow the service name to appear under the GOV.UK Header as per rebranding instructions -https://companieshouse.atlassian.net/wiki/spaces/DEV/pages/5479530596/How+to+Enable+the+GOV.UK+Rebrand+in+Node.js+Web+Applications
We are committed to keeping commit history clean, consistent and linear. To achieve this, this commit should be structured as follows:
```
<type>[optional scope]: <description>
```
and contain the following structural elements:
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic versioning),
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR …
> IDVA5-2454 implemented new header 

- src/middleware/content_security_policy_middleware_config.ts
Trying all hardcoded urls:
```
"https://*.chdev.org",
"https://*.cidev.aws.chdev.org",
"https://cidev.aws.chdev.org",
"https://cidev.aws.chdev.org/register-as-companies-house-authorised-agent",
"https://cidev.aws.chdev.org/register-as-companies-house-authorised-agent/check-saved-application",
"https://cidev.aws.chdev.org/signin",
"https://account.cidev.aws.chdev.org",
"https://identity.company-information.service.gov.uk"
```
> IDVA5-2592 Adding all hardcoded urls with protocols added

- README.md
Further updates and corrections on repository readme.md file
> Updating the repo readme
