locales/cy/correspondence-address-manual.json
locales/cy/corresspondence-address-lookUp.json
locales/en/correspondence-address-manual.json
locales/en/corresspondence-address-lookUp.json
src/main/validation/correspondenceAddressAutoLookup.ts
src/main/validation/correspondenceAddressManual.ts
src/test/src/validation/correspondenceAddressLookUp.test.ts
src/test/src/validation/correspondenceAddressManual.test.ts

Adding new error message for What is your correspondence address screens. When user put half post code they will get this error "Enter a full UK postcode" and when user give a input rather than letters from a to z, numbers and spaces they will get this error message "Postcode must only include letters a to z, numbers and spaces". In this PR I have added both error message with welsh translation and unit tests.

Adding new error message

---

src/main/router.dispatch.ts
src/main/types/pageURL.ts
src/main/views/partials/__footer.njk
src/main/views/partials/__header.njk
src/test/e2e/features/stopnotrelevantofficerRouter.ts
src/test/src/controllers/indexController.test.ts
src/test/src/controllers/otherTypeOfBusinessController.test.ts
src/test/src/controllers/soleTradercorrespondenceAddressConfirmController.test.ts

changes context path.
footer.njk and header.njk still uses hardcoded urls, as every controller need to be updated if we want to use reference which is a big job.

pageurls - fix context path

---

src/main/common/__utils/constants.ts
src/main/controllers/features/limited/whatIsYourRoleController.ts
src/main/controllers/features/limited/whichSectorOtherController.ts
src/main/controllers/features/sole-trader/nameController.ts
src/main/controllers/features/sole-trader/sectorYouWorkInController.ts
src/main/controllers/features/sole-trader/typeOfBusinessController.ts
src/main/controllers/features/sole-trader/whatIsYourRoleController.ts
src/main/controllers/features/sole-trader/whichSectorOtherController.ts
src/main/controllers/features/unincorporated/unincorporatedWhatIsYourRoleController.ts
src/main/controllers/features/unincorporated/whatIsTheBusinessNameController.ts
src/main/controllers/features/unincorporated/whichSectorOtherController.ts
src/main/middleware/authentication_middleware.ts
src/main/model/ACSPData.ts
src/main/services/address/addressLookUp.ts
src/main/services/business-address/businessAddressService.ts

> Acspdata model is changed to include id. First name and last name are made optional as all journeys don't have this screen
> User login id is captured in types-of-business page and set into session 
> Refactored code to remove use of field ACSP_TYPE. Instead use ACSPData.typesOfBusiness
> Auth middleware return url is changed to land on 'types of business' page

model changes to include id and session changes to set the id

---

src/services/where-do-you-live/whereDoYouLive.ts
src/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
test/src/services/transaction/transaction_service.test.ts
test/src/services/where-do-you-live/whereDoYouLive.test.ts

Removed hyphen from Northern Ireland value in njk file
Updated the service to repopulate the data after removing hyphen

Fixed Northern Ireland being hyphenated on Check your answers screen

---

locales/cy/what-is-your-role.json
locales/en/what-is-your-role.json
src/views/common/index/home.njk
src/views/common/sector-you-work-in/sector-you-work-in.njk
src/views/common/what-is-your-role/what-is-your-role.njk

- The role type page is dynamically populated depending on which business type the user had selected previously in the Registration service (i.e. If the user selected Sole Trader, they would be presented with the radio option "I am the sole trader" on the 'What is your role in the business?' page). 
- As these radio options are dynamic depending on the business type, Matomo was failing to capture the relevant id of the event. Conditional logic has now been added to capture the role type analytics.
- Adding Matomo event action to capture when user presses the 'Start now' button.
- Updated Matomo script to capture full text: "Auditors, insolvency practitioners, external accountants and tax advisers"
- Updated naming of JSON title key

Fixing issue with Matomo not capturing business role event

---

src/views/common/what-is-your-role/what-is-your-role.njk

Updating logic to capture analytics against the middle radio option on what is your role page, when user selects Unincorporated or Corporate Body journeys.

Fixing Matomo bug on radio selection event action

---

locales/cy/sector-you-work-in.json
locales/en/sector-you-work-in.json
src/controllers/features/limited/sectorYouWorkInController.ts
src/controllers/features/sole-trader/sectorYouWorkInController.ts
src/controllers/features/unincorporated/unincorporatedSectorYouWorkInController.ts
src/routes/index.ts
src/services/checkYourAnswersService.ts
src/validation/sectorYouWorkIn.ts
src/views/common/sector-you-work-in/sector-you-work-in.njk
src/views/partials/piwik.njk
test/mocks/check_your_answers.mock.ts
test/src/controllers/limited/sectorYouWorkInController.test.ts
test/src/controllers/soleTrader/sectorYouWorkInController.test.ts
test/src/controllers/unincorporated/sectorYouWorkInController.test.ts
test/src/services/checkYourAnswersService.test.ts

- Work sector page is now optional and can be skipped.
- Removed validation text.
- Deleted validator file and all references to this from the code base.
- Removed relevant error handling from POST requests on controllers for each journey.
- Added hint text to page.
- Added Matomo function to listen for changes in radio button selections and track the selected radio button.
- Updated Matomo analytics to capture based on if the user has selected a radio option or skipped the page, when pressing the save and continue button.
- Updating check your answers page to set work sector as 'Not provided' if work sector has been skipped
- Updated tests and code coverage

Updating work sector page as selection is now optional

---

src/views/common/sector-you-work-in/sector-you-work-in.njk
src/views/partials/piwik.njk

save-and-continue button was being tracked multiple times when selecting between radio options on work sector page. 
Issue was with loop calling the function each time a radio was selected on this page and logging the analytics

Fixing matomo bug on sector you work in page

---

locales/cy/application-submitted.json
locales/cy/start-page.json
locales/en/application-submitted.json
locales/en/start-page.json
src/views/common/correspondence-address-confirm/correspondence-address-confirm.njk
src/views/features/unincorporated/confirm-your-business-address/confirm-your-business-address.njk

- Added Matomo function to gather analytics for 'Edit address' link on 'Confirm the correspondence address' and 'Confirm the business address' pages.
- Small text change on home page and application submitted page to match prototype 14

Small fix for Matomo event tracking and text update

---

src/views/features/unincorporated/business-address-manual-entry/business-address-manual-entry.njk

Fixing display bug on Enter Business Address Manual screen.
Property name/number field was not populating with session data after navigating back to the manual address entry page after previous user input.
[IDVA5-1306](https://companieshouse.atlassian.net/browse/IDVA5-1306)
The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)
[IDVA5-1306]: https://companieshouse.atlassian.net/browse/IDVA5-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

Updating payload value to grab property number from session

---

src/controllers/features/common/savedApplicationController.ts
src/controllers/features/common/typeOfBusinessController.ts
src/controllers/features/unincorporated/unincorporatedNameRegisteredWithAmlController.ts
src/middleware/common_variables_middleware.ts
src/services/acspDataService.ts
test/src/services/acspDataService.test.ts

Clearing USER_DATA session variable when user selects a new type of business.
USER_DATA also includes links and acsp-data-submission details which must be kept, so adding those back to USER_DATA once its has been cleared.

Cleared session data when user selects a new type of business

---

src/views/common/stop-not-relevant-officer/stop-not-relevant-officer.njk
src/views/features/limited/business-mustbe-aml-registered/business-mustbe-aml-registered.njk
src/views/features/limited/company-inactive/company-inactive.njk

Override signoutBar component to remove 'govuk-section-break--visible' border from section break when back button is disabled for following kickout screens:
- /cannot-use-service
- /limited/your-business-must-be-aml-registered
- /limited/company-inactive
[IDVA5-1328](https://companieshouse.atlassian.net/browse/IDVA5-1328)
[IDVA5-1328]: https://companieshouse.atlassian.net/browse/IDVA5-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove section break border when back button is hidden

---

package-lock.json
package.json
src/controllers/features/common/checkSavedApplicationController.ts
src/controllers/features/common/savedApplicationController.ts
src/controllers/features/common/typeOfBusinessController.ts
src/services/acspRegistrationService.ts
src/services/checkSavedApplicationService.ts
src/services/transactions/transaction_service.ts
test/src/controllers/common/checkSavedApplicationController.test.ts
test/src/controllers/common/typeOfBusinessController.test.ts
test/src/services/acspRegistrationService.test.ts
test/src/services/checkSavedApplicationService.test.ts
test/src/services/transaction/transaction_service.test.ts

- Filtered out rejected applications to prevent the wrong page being displayed when a user attempts to create a new application after a rejected one.
- Updated delete application to also delete the transaction associated with when when user selects to create a new application and not continue an old one.
- Moved calling POST transaction back to the get request in what type of business controller

IDVA5-1311 Fixed wrong page being displayed after an application is rejected

---

src/views/partials/error_500.njk

Override signoutBar component to remove 'govuk-section-break--visible' border from section break when back button is disabled for error_500 technical difficulties screen found during testing.
[IDVA5-1328](https://companieshouse.atlassian.net/browse/IDVA5-1328)
[IDVA5-1328]: https://companieshouse.atlassian.net/browse/IDVA5-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix visual bug fix for error 500 screen

---

src/config/index.ts
src/controllers/features/common/resumeJourneyController.ts
src/services/transactions/transaction_service.ts
src/utils/properties.ts
test/mocks/payment_mock.ts
test/mocks/transaction_mock.ts
test/src/controllers/common/resumeJourneyController.test.ts
test/src/services/transaction/transaction_service.test.ts

- Check users transaction status when they are sent back from your filings page
- If status is closed pending payment we direct them to pay
- else we direct them to the type of business screen

Redirect user directly to payment if they resume a transaction that is closed pending payment

---

locales/cy/sector-you-work-in.json
locales/cy/which-sector-other.json
locales/en/sector-you-work-in.json
locales/en/which-sector-other.json
src/controllers/features/limited/sectorYouWorkInController.ts
src/controllers/features/sole-trader/sectorYouWorkInController.ts
src/controllers/features/unincorporated/unincorporatedSectorYouWorkInController.ts
src/model/BusinessSector.ts
src/routes/index.ts
src/services/checkYourAnswersService.ts
src/validation/sectorYouWorkIn.ts
src/validation/whichSectorOther.ts
src/views/common/sector-you-work-in/sector-you-work-in.njk
src/views/common/which-sector-other/which-sector-other.njk
test/mocks/check_your_answers.mock.ts
test/src/controllers/common/amlBodyMembershipNumberController.test.ts
test/src/controllers/limited/sectorYouWorkInController.test.ts
test/src/controllers/limited/whatIsYourEmailAddressController.test.ts
test/src/controllers/limited/whichSectorOtherController.test.ts
test/src/controllers/soleTrader/sectorYouWorkInController.test.ts
test/src/controllers/soleTrader/whatIsYourEmailAddressController.test.ts
test/src/controllers/soleTrader/whatIsYourRoleController.test.ts
test/src/controllers/soleTrader/whichSectorOtherController.test.ts
test/src/controllers/unincorporated/sectorYouWorkInController.test.ts
test/src/controllers/unincorporated/sectorYouWorkInOtherController.test.ts
test/src/controllers/unincorporated/whatIsYourEmailAddressController.test.ts
test/src/services/checkYourAnswersService.test.ts

Includes changes against 2 tickets.
**Ticket 1: IDVA5-1316**
- Added Radio button validation to both Work Sector and Other Work Sector pages as they can no longer be skipped
- Removed hint text on both work sector pages
- Updated text for 'Other' radio option on work sector page
- Added additional Radio button 'Prefer not to say'
- Updated Matomo analytics implementation for both work sector pages - now tracks new radio option and removed analytics if page was skipped (page can no longer be skipped)
- Updated Controller Post requests on all journeys to capture radio button validation
- Updated check your answers implementation to match new Radio option (previously Work Sector would display as 'Not provided' if page was skipped)
- …

Updating work sector implementation

---

package-lock.json
package.json
src/model/ACSPData.ts
src/model/AcspType.ts
src/services/acspDataService.ts
test/src/services/acspDataService.test.ts

New field acsp_type added to the acspData object being saved to Mongo DB to store values e.g. register-acsp, update-acsp, delete-acsp. Have hardcoded it to enum 'REGISTER_ACSP' for now but this should be changed later when we work on the Update ACSP Details tickets.
Tested locally appearing in DB as:
[IDVA5-1433](https://companieshouse.atlassian.net/browse/IDVA5-1433)
[IDVA5-1433]: https://companieshouse.atlassian.net/browse/IDVA5-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

Adding new field acsp_type to acspData object

---

locales/en/payment-failed.json
src/views/common/payment-failed/payment-failed.njk

Removing additional full stop after web link and adding full stop to end of sentence on payment failed screen

fixing ui issue on payment failed screen

---

src/controllers/features/common/checkYourAnswers.ts
src/services/paymentService.ts

Adding logs when creating payment session in web to check if the multiple calls to cost endpoint are caused by an issue within ACSP-WEB

Adding logs for creating payment session

---

src/middleware/company_authentication_middleware.ts
test/src/middleware/company_authentication_middleware.test.ts

Removing the need for companyAuthCodeProvided flag. We dont need this flag checking as this work is automatically done by Auth Middleware

Removing the need for companyAuthCodeProvided flag.

---

src/middleware/authentication_middleware.ts
test/src/middleware/authentication_middleware.test.ts

Updating routing for the Update ACSP Details start page through using a regular expression to check the endpoint matches the update acsp endpoint, whilst also checking if the feature flag has been enabled for the service.
If both checks result to true, then the user will be routed directly to the Update ACSP Details start page when directly navigating to the endpoint (after log in).
Previously when a user navigated directly to the endpoint of the Update ACSP Service, they would be asked to login, upon logging in, they would then be routed to the 'Do you want to start a new application' page on the registration service rather than the Update ACSP start page. This change should fix this behaviour.

Updating routing for update acsp details start page

---

locales/cy/common-address-manual.json
locales/en/common-address-manual.json
src/views/common/correspondence-address-manual/capture-correspondence-address-manual.njk

Removing inset text on Correspondence Address page.
Ticket:
[IDVA5-1595](https://companieshouse.atlassian.net/browse/IDVA5-1595)
[IDVA5-1595]: https://companieshouse.atlassian.net/browse/IDVA5-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removing inset text correspondence address

---

src/app.ts

https://companieshouse.atlassian.net/browse/IDVA5-1605
Companies You Follow link was not working in the new navbar in cidev. Have added this line in app.ts. Locally I can see the url follow.chs.local so it should link correctly in cidev now.

IDVA5-1483 Fix for companies you follow link

---

src/controllers/features/sole-trader/whereDoYouLiveController.ts
src/controllers/features/update-acsp/whereDoYouLiveController.ts
src/services/where-do-you-live/whereDoYouLive.ts
src/views/common/correspondence-address-manual/capture-correspondence-address-manual.njk
src/views/partials/country-typeahead-input.njk
test/src/services/where-do-you-live/whereDoYouLive.test.ts

Updating where do you live service to return a single payload object.
Updating the country-typeahead-input to get default value from payload like other inputs

Fixing Correspondence address country input not showing on back

---

src/controllers/features/common/checkYourAnswers.ts
src/controllers/features/common/paymentCallbackController.ts
src/controllers/features/common/resumeJourneyController.ts
src/services/paymentService.ts
src/utils/localise.ts
src/views/common/application-confirmation/application-confirmation.njk
src/views/layouts/default.njk
test/mocks/request.mock.ts
test/src/services/paymentService.test.ts
test/src/utils/localise.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-1719
- Added lang to return uri to store en/cy and return users to the confirmation screen in that language
- Removed language switch from confirmation view to prevent users switching and throwing error caused by clearing the session data
- Updated tests

Add lang to payment return uri, remove lang select on confirmation view

---

src/controllers/features/common/amlBodyMembershipNumberController.ts
test/src/controllers/common/amlBodyMembershipNumberController.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-1733
- Refactored the errorListDisplay function in amlBodyMembershipNumberController to get the value from AMLSupervisoryBodies Enums and include this in the error message rather than the abbreviation
- Added mock value of ACCA for unit test scenarios with errors displayed

Refactor controller to include AML values in errors

---

src/controllers/features/limited/companyLookupController.ts
test/src/controllers/limited/companyLookupController.test.ts

It was discovered during the testing of [IDVA5-915](https://companieshouse.atlassian.net/browse/IDVA5-915?atlOrigin=eyJpIjoiMTcyN2EzZDRjYTkyNGU4YmI5MTAxNWMzM2NmZjg3MzMiLCJwIjoiaiJ9) that when the on the company number input screen and the authorisation token had expired after idle time, upon entering a valid company number, the application was throwing the validation message "Enter a valid company number".
This was due to the controller encountering the first catch block on the POST request and halting the service, rather than filtering through to the second catch block and redirecting the user to sign in > checked saved application page.
Updated the first catch block to only catch the validation error when the company number is not valid. 
If the authorisation token has expired after …

Updating catch clause on company lookup

---

locales/cy/update-your-details.json

Updating Welsh translation for continue to payment.
Check your answers .njk file was pulling in continueToPayment translation for update-your-details.json file

Updating welsh translation

---

locales/cy/address-look-up.json
locales/cy/common-address-confirm.json
locales/cy/common-address-manual.json
locales/en/address-look-up.json
locales/en/common-address-confirm.json
locales/en/common-address-manual.json
src/controllers/features/update-acsp/businessAddressAutoLookupController.ts
src/controllers/features/update-acsp/businessAddressConfirmController.ts
src/controllers/features/update-acsp/businessAddressManualController.ts
src/views/features/unincorporated/business-address-auto-lookup/auto-lookup-address.njk
src/views/features/unincorporated/business-address-manual-entry/business-address-manual-entry.njk
src/views/features/unincorporated/confirm-your-business-address/confirm-your-business-address.njk
src/views/partials/update-your-details/limited-answers.njk

https://companieshouse.atlassian.net/browse/IDVA5-1461
- Limited journey doesn't have office address screens in Registration so I am reusing the 'Business address' screens for Unincorporated journey.
- I set the title and h1 according to the business type from AcspFullProfile so if it matches "limited-company", "limited-liability-partnership" or "corporate-body" then it will be 'Registered address' otherwise keep it as 'Business address' as in current Unincorporated flow.
- I did some sanity checks on Registration service and also Update ACSP as unincorporated and it was displaying correctly

IDVA5-1461 Limited registered office address screens for Update ACSP

---

locales/cy/cancel-all-updates.json
locales/en/cancel-all-updates.json
src/config/index.ts
src/controllers/features/update-acsp/cancelAllUpdatesController.ts
src/controllers/features/update-acsp/updateYourDetailsController.ts
src/controllers/index.ts
src/routes/updateAcsp.ts
src/types/pageURL.ts
src/views/features/update-acsp-details/cancel-all-updates/cancel-all-updates.njk
src/views/features/update-acsp-details/update-your-details.njk
test/src/controllers/updateAcspDetails/cancelAllUpdatesController.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-1713
- Added cancel all updates screen upon clicking 'cancel' link on update details screen based on new prototype below
- New controller to clear the acspUpdatedFullProfile from session in post method when clicking continue
- Added manage users url for redirect

Added cancel all updates screen and tests

---

src/controllers/features/update-acsp/addAmlSupervisorController.ts
src/controllers/features/update-acsp/updateYourDetailsController.ts
src/model/AMLSupervisoryBodiesFormatted.ts
test/src/controllers/updateAcspDetails/addAmlSupervisorController.test.ts

Fixing the below:
1. On New AML Body screen HMRC should appear in order of alphabetic.
2. In the AML ref number page on clicking of the back button the radio button should be pre selected with the AML body chosen earlier.

IDVA5-1706 Add a new AML body

---

locales/cy/update-your-details.json
locales/en/update-your-details.json
src/views/features/update-acsp-details/update-your-details.njk
src/views/layouts/default.njk

https://companieshouse.atlassian.net/browse/IDVA5-1812
Following changes made as part of v4 prototype:
- /update-your-details screen size changed from 2/3 to 3/4. I added a block around this in default.njk so I could override the class just for this screen in update-your-details.njk. Other screens remain 2/3 and have tested this in Registration also.
- blue notification banner added to the top
- inset text removed
- new content added in AML section

View and update details v4 prototype changes

---

src/controllers/features/update-acsp/correspondenceAddressManualController.ts
src/services/correspondence-address/correspondence-address-manual.ts
test/src/services/correspondence-address/correspondence-address-manual.test.ts

This bug was preventing the country field being pre-populated when a sole trader updated their correspondence address and went to the manual address page.
Updated the getCorrespondenceManualAddressUpdate to accept an address and then used this to populate the fields. Previously it was using getBusinessManualAddress function which has a different input name for country field.

Updating service address to show country for sole trader

---

src/services/business-address/businessAddressService.ts
src/validation/correspondenceAddressManual.ts
test/src/controllers/updateAcspDetails/correspondenceAddressManualController.test.ts

Allowing country on manual correspondence address screen to be entered in a case insensitive way as data from data sync comes back in call capitals.
Updating the country check in formatCountry function to check for null and undefined.

Fixing bugs on manual address screens

---

package-lock.json
src/controllers/features/update-acsp/updateYourDetailsController.ts
src/views/features/update-acsp-details/update-your-details.njk

https://companieshouse.atlassian.net/browse/IDVA5-1812
Removed 'Go back to authorised agent services' button in AML details section and added it as text link at bottom of page to match the v4 prototype.
This text link will not be shown once an update has been made.

Remove button and add new text link

---

src/services/errorService.ts

Bug fix for ticket: [IDVA5-1946](https://companieshouse.atlassian.net/browse/IDVA5-1946?atlOrigin=eyJpIjoiNzEwNjVhYzc4N2E2NDBlN2IzNDFiZWU0NzMzOWMzMjkiLCJwIjoiaiJ9)
It was discovered that during test of the Welsh language, upon navigating to the 'Page not found screen' and selecting the Welsh language toggle, the user would be redirected to the URL chs.local/?lang=cy, rather than refreshing the page with Welsh language visible.
Updated the currentUrl value of the render404Page function to redirect to the original URL of the 404 page when using the Welsh language toggle
[IDVA5-1946]: https://companieshouse.atlassian.net/browse/IDVA5-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fixing redirection issue when using welsh toggle on 404 page

---

src/views/common/accessibility-statement/accessibility-statement.njk

Wording update 'customers' to 'users' to match prototype
Removing text content from accessibility statement that are redundant for the Registration service (following confirmation from PM for removal)

wording change on accessibility stament

---

src/controllers/features/update-acsp/businessAddressManualController.ts
src/services/business-address/businessAddressService.ts

Updating the manual business address to not show an update if the country does not change
Previously it was changing the address to be lower case and so showing as an update. This change checks to see if the countries are the same when case is ignored

Updating the manual business address to not show an update if the country does not change

---

src/controllers/features/common/resumeJourneyController.ts
test/mocks/transaction_mock.ts
test/src/controllers/common/resumeJourneyController.test.ts

The technical error screen was showing when resuming from filings because when the user is redirected to login the acspId query parameter is lost. This resulted in the user being shown a technical error page due to the get request failing with no application Id
Fix: Getting applicationId from the transaction if it does not get returned by the resume journey link
Also removing code smells from this file

Fixing technical error screen being shown when resuming from filings

---

src/controllers/features/common/amlBodyMembershipNumberController.ts
src/controllers/features/common/checkAmlDetailsController.ts
src/views/common/check-aml-details/check-aml-details.njk

- Updated the error messages on AML membership number page to include the translated AML body names
- Updated the link on the check AML details page to add the language so when the user edits an AML body in Welsh they are taken back to the AML membership number page in Welsh

Updating AML bodies to use Welsh names

---

locales/cy/common.json
locales/en/common.json
src/views/common/application-confirmation/application-confirmation.njk
src/views/common/index/home.njk
src/views/common/stop-not-relevant-officer/stop-not-relevant-officer.njk
src/views/features/limited/company-number/company-number.njk
src/views/partials/__header.njk
src/views/partials/cookie_consent_banner.njk

Adding opens in new tab to feedback and guidance links except on the start page where they open in the same tab

Fixing accessibility issues on links opening in a new tab

---

locales/cy/address-correspondence-selector.json
locales/en/address-correspondence-selector.json
test/src/controllers/limited/addressCorrespondanceSelectorController.test.ts
test/src/controllers/unincorporated/addressCorrespondanceSelectorController.test.ts

Changes made for ticket:
[IDVA5-1913](https://companieshouse.atlassian.net/browse/IDVA5-1913?atlOrigin=eyJpIjoiZDM0YWMzMGYxNTkyNDg5Zjg0ZDRlYzU1YTk5NDAzYzciLCJwIjoiaiJ9)
- Updating the page title for the address correspondence selector common screen to align with DAC adjustments.
- Updated from "What is the correspondence address?" to "What address should we use for correspondence?"
- Updated Welsh translation
- Updated unit tests
[IDVA5-1913]: https://companieshouse.atlassian.net/browse/IDVA5-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating correspondence address page title for DAC change

---

src/views/common/check-aml-details/check-aml-details.njk

Ticket: [IDVA5-1994](https://companieshouse.atlassian.net/browse/IDVA5-1994)
Adding span to show the AML body name on change link for screen readers on the Check AML details page
[IDVA5-1994]: https://companieshouse.atlassian.net/browse/IDVA5-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding span to show the aml body name on change link

---

src/controllers/features/update-acsp/amlMembershipNumberController.ts
src/controllers/features/update-acsp/businessAddressConfirmController.ts
src/controllers/features/update-acsp/businessAddressListController.ts
src/controllers/features/update-acsp/businessAddressManualController.ts
src/controllers/features/update-acsp/correspondenceAddressConfirmController.ts
src/controllers/features/update-acsp/correspondenceAddressListController.ts
src/controllers/features/update-acsp/correspondenceAddressManualController.ts
src/controllers/features/update-acsp/whatIsTheBusinessNameController.ts
src/controllers/features/update-acsp/whatIsYourNameController.ts
src/controllers/features/update-acsp/whereDoYouLiveController.ts
src/middleware/update-acsp/update_variables_middleware.ts
src/views/common/correspondence-address-confirm/correspondence-address-confirm.njk
src/views/common/correspondence-address-manual/capture-correspondence-address-manual.njk
src/views/common/correspondence-auto-lookup-address/auto-lookup-address.njk
src/views/common/correspondence-auto-lookup-address/correspondence-address-list.njk
src/views/common/name/capture-name.njk
src/views/common/what-is-the-business-name/what-is-the-business-name.njk
src/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
src/views/features/unincorporated/business-address-auto-lookup/auto-lookup-address.njk
src/views/features/unincorporated/business-address-auto-lookup/business-address-list.njk
src/views/features/unincorporated/business-address-manual-entry/business-address-manual-entry.njk
src/views/features/unincorporated/confirm-your-business-address/confirm-your-business-address.njk
src/views/features/update-acsp-details/add-aml-supervisory-body/add-aml-supervisory-body.njk
src/views/features/update-acsp-details/what-is-your-email/what-is-your-email.njk

Changes made for ticket:
[IDVA5-1861](https://companieshouse.atlassian.net/browse/IDVA5-1861?atlOrigin=eyJpIjoiNDYwNjdkYjc1MTNiNDBkMmI4MTFjMzIwOGI4ZGFlNzgiLCJwIjoiaiJ9)
- Adding 'Cancel update' link to all screens where a user can update their details, which is checked against `{% if reqType === "updateAcsp" %}` on all applicable view files
- The above change excludes the 'Add AML Details' screens, as a user is adding new AML details and not updating existing details
- When a user interacts with the 'Cancel update' link, they will be routed to the main page of the Update ACSP Details service
- Removing the `res.locals.reqType = REQ_TYPE_UPDATE_ACSP;` line from individual controllers within the Update ACSP service
- Adding `res.locals.reqType = REQ_TYPE_UPDATE_ACSP;` to the …

Adding cancel update link to all applicable update acsp details screens

---

src/controllers/features/update-acsp/businessAddressConfirmController.ts
src/controllers/features/update-acsp/businessAddressListController.ts
src/controllers/features/update-acsp/correspondenceAddressConfirmController.ts
src/controllers/features/update-acsp/correspondenceAddressListController.ts

Fix for ticket:
[IDVA5-1861](https://companieshouse.atlassian.net/browse/IDVA5-1861?atlOrigin=eyJpIjoiYTg5ZjlkZjVhNWNjNDlmYmE4MWE0NWU0YjczODU3Y2IiLCJwIjoiaiJ9)
- Fixing an issue of updated session data not cleared from find address screen when user interacts with 'Cancel update' link on Select address and Confirm address screens
- Used existing cancel update service to clear the updated session data for the address screens
[IDVA5-1861]: https://companieshouse.atlassian.net/browse/IDVA5-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clearing the updated address session data when user clicks cancel update

---

locales/cy/common.json
locales/en/common.json
src/middleware/registration_variables_middleware.ts
src/middleware/update-acsp/update_variables_middleware.ts
src/views/features/update-acsp-details/update-your-details.njk
src/views/partials/__meta_header.njk

Changes made for ticket:
[IDVA5-2022](https://companieshouse.atlassian.net/browse/IDVA5-2022?atlOrigin=eyJpIjoiMWZkNWViMDUzNDcxNDVmY2I0MmVkYTA5YjAyMzQ2MDUiLCJwIjoiaiJ9)
- Splitting out the Nunjucks logic within the <title> tag of the meta_header.njk 
- Assigning the common tab titles within <service_name>_variables_middleware for each service to avoid hard coded serviceUrl check in njk file
- Updating the size of the heading display on the main page on Update your details (reduced from extra large to large text)
- These changes fix the display issue seen on Matomo when interacting with the Update ACSP Details service, as it will now show the correct service title depending on the service the user is interacting with
[IDVA5-2022]: …

Fixing an issue with tab and matomo text update acsp details service

---

src/controllers/features/update-acsp/businessAddressManualController.ts
src/controllers/features/update-acsp/correspondenceAddressManualController.ts

Fix for ticket returned from test:
[IDVA5-1861](https://companieshouse.atlassian.net/browse/IDVA5-1861?atlOrigin=eyJpIjoiYWE0OGRiOGMxNDE2NGYzMmIwOWRjNDE5MThjOGRjMjEiLCJwIjoiaiJ9)
- Updated 'Cancel update' link on manual address entry screens within Update ACSP Details service to allow clearing of session data saved when interacting with Cancel update link for all 3 journey types
[IDVA5-1861]: https://companieshouse.atlassian.net/browse/IDVA5-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fxing issue on manual address entry screen cancel update link

---

src/controllers/features/update-acsp/whatIsTheBusinessNameController.ts
src/services/update-acsp/yourUpdatesService.ts
src/views/partials/update-your-details/limited-answers.njk
src/views/partials/update-your-details/sole-trader-answers.njk
src/views/partials/update-your-details/unincorporated-answers.njk
test/src/controllers/updateAcspDetails/whatIsTheBusinessNameController.test.ts
test/src/services/update_acsp/yourUpdatesService.test.ts

Ticket [IDVA5-1985](https://companieshouse.atlassian.net/browse/IDVA5-1985)
- Updated the routing for change of business name screen to take the user to when did this change
- Saving user input for date change to the a temporary variable until they have entered the date of change
- Showing the date of change on the view and update details screen
[IDVA5-1985]: https://companieshouse.atlassian.net/browse/IDVA5-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding the date of change to business name

---

src/views/features/unincorporated/business-address-auto-lookup/auto-lookup-address.njk

Fix for ticket:
[IDVA5-2027](https://companieshouse.atlassian.net/browse/IDVA5-2027?atlOrigin=eyJpIjoiNThkYTRlMzlhNDcxNGYwMDg3MGU3ZWQ0ZGJlNDQ1YjMiLCJwIjoiaiJ9)
- Fixing issue where the inset styling for text was appearing on Unincorporated Business Address lookup screen
[IDVA5-2027]: https://companieshouse.atlassian.net/browse/IDVA5-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

hiding inset text display reg office address unincorporated

---

src/controllers/features/update-acsp/businessAddressAutoLookupController.ts
src/controllers/features/update-acsp/businessAddressConfirmController.ts
src/controllers/features/update-acsp/businessAddressListController.ts
src/controllers/features/update-acsp/businessAddressManualController.ts
src/services/address/addressLookUp.ts
src/services/business-address/businessAddressService.ts
src/services/update-acsp/yourUpdatesService.ts
src/views/partials/update-your-details/limited-answers.njk
src/views/partials/update-your-details/unincorporated-answers.njk
test/src/controllers/updateAcspDetails/businessAddressConfirmController.test.ts
test/src/services/address/addressLookup.test.ts

Ticket [IDVA5-1986](https://companieshouse.atlassian.net/browse/IDVA5-1986)
- Updated the routing for change of registered office address screens to take the user to when did this change
- Saving user input for registered office address change to the a temporary variable until they have entered the date of change
- Showing the date of change on the view and update details screen
[IDVA5-1986]: https://companieshouse.atlassian.net/browse/IDVA5-1986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding change of date to registered office address page

---

src/controllers/features/limited/correspondenceAddressAutoLookupController.ts
src/controllers/features/sole-trader/correspondenceAddressAutoLookupController.ts
src/controllers/features/unincorporated/businessAddressAutoLookupController.ts
src/controllers/features/unincorporated/correspondenceAddressAutoLookupController.ts
src/services/address/addressLookUp.ts
test/src/controllers/limited/correspondenceAddressLookUp.test.ts
test/src/controllers/soleTrader/correspondenceAddressAutoLookupController.test.ts
test/src/controllers/unincorporated/businessAddressLookUpController.test.ts
test/src/controllers/unincorporated/correspondenceAddressLookUpController.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-2046
fixing the test issue
The exception thrown was overwritten by the default catch call, implementing the conditional catch

ACSP Registration - Show Error and Allow User to use Manual Address Entry Screen for ''Border'' Postcode Lookup Issue

---

locales/cy/what-is-the-business-name.json
locales/en/what-is-the-business-name.json
src/validation/unicorporatedWhatIsTheBusinessName.ts
test/src/controllers/updateAcspDetails/whatIsTheBusinessNameController.test.ts

Changes made against ticket:
[IDVA5-2050](https://companieshouse.atlassian.net/browse/IDVA5-2050?atlOrigin=eyJpIjoiZDI5Y2JkN2RmMDUwNDY3MWJmOTIwMGRjZmJjZTU5ZTAiLCJwIjoiaiJ9)
- We use the existing unincorporatedWhatIsTheBusinessName validation for the Business Name validation within Update ACSP Details service
- Added custom validation that checks if no changes has been made to the original business name (ACSP_DETAILS) and the user attempts to press continue to the next page
- Before checking the existing value against the inputted data, both the inputted and existing business names are converted to lower case, leading and trialing spaces removed and additional spaces removed.
See below for some scenarios of the above:
Input Business Name | Existing Business Name | Result
-- | -- | -- …

adding validation for business name if no changes made

---

src/common/__utils/constants.ts
src/common/__utils/sessionHelper.ts
src/controllers/features/update-acsp/dateOfTheChangeController.ts
src/controllers/features/update-acsp/updateYourDetailsController.ts
src/controllers/features/update-acsp/yourUpdatesController.ts
src/services/update-acsp/amlSupervisorService.ts
src/services/update-acsp/yourUpdatesService.ts
src/views/features/update-acsp-details/date-of-the-change/date-of-the-change.njk
src/views/features/update-acsp-details/update-your-details.njk
test/src/controllers/updateAcspDetails/dateOfTheChangeController.test.ts
test/src/services/update_acsp/amlSupervisorService.test.ts
test/src/services/update_acsp/yourUpdatesService.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-2082
- Added dateOfChange screen to the flow for Remove AML. The 'Remove' links on Update Your Details previously called the removeAmlSupervisorController but now go to dateOfChange for pre-existing AML bodies, and retains the removeAmlSupervisorController url for newly added AML bodies.
- The amlIndex and amlBody are being passed as query params as before but to dateOfChange screen where they are saved in the session.
- As the AML body details are removed from acspUpdatedFullProfile I created a session variable AML_REMOVED_BODY_DETAILS to store the body, membershipId and dateOfChange which can then be accessed on the views to display to the user.
- If an AML is removed and then this is cancelled, AML_REMOVED_BODY_DETAILS is updated to …

IDVA5-2082 Remove AML with date of change

---

src/views/partials/piwik.njk

https://companieshouse.atlassian.net/browse/IDVA5-2064
Same approach we did on Verify A Client to stop the tracking of the user email in Matomo when clicking it on the mobile navbar. Will now track as this:

Fix to not track user email in Matomo from mobile navbar

---

src/controllers/features/update-acsp/addAmlSupervisorController.ts
src/views/features/update-acsp-details/update-your-details.njk
src/views/partials/your-updates-add-aml.njk
test/src/controllers/updateAcspDetails/addAmlSupervisorController.test.ts

The edit option of a newly added AML wasn't working due to incorrect url formation with the wrong parameters. Fixed it by:
- Modifying the query strings
- Modifying the njks
https://companieshouse.atlassian.net/browse/IDVA5-2101

IDVA5-2101 Update ACSP - Your Updates - AML edit links

---

src/controllers/features/update-acsp/businessAddressAutoLookupController.ts
src/controllers/features/update-acsp/correspondenceAddressAutoLookupController.ts
src/services/address/addressLookUp.ts
test/src/controllers/updateAcspDetails/businessAddressAutoLookupController.test.ts
test/src/controllers/updateAcspDetails/correspondenceAddressAutoLookupController.test.ts

On a situation of a postcode search returning country value as "" we are throwing the exception as given below:
https://companieshouse.atlassian.net/browse/IDVA5-2104

ACSP Update - Show Error and Allow User to use Manual Address Entry Screen for ''Border'' Postcode Lookup Issue

---

src/views/features/update-acsp-details/date-of-the-change/date-of-the-change.njk

Ticket [IDVA5-2085](https://companieshouse.atlassian.net/browse/IDVA5-2085)
Removing autocomplete attribute from date of change field as it does not match a valid autocomplete attribute value 
https://www.w3schools.com/tags/att_input_autocomplete.asp
[IDVA5-2085]: https://companieshouse.atlassian.net/browse/IDVA5-2085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removing autocomplete attribute from date of change field

---

src/services/update-acsp/amlMembershipNumberService.ts
test/src/services/update_acsp/dateOfTheChangeService.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-1849
When using 'Edit' link on Your Updates or 'Update' on Check Your Answers, the updated dateOfChange value was not being saved with the New AML Details. 
I've added this line in to allow it to be updated now.

Allow dateOfChange to be updated and displayed after edit New AML

---

locales/cy/what-is-the-business-name.json
locales/en/what-is-the-business-name.json
src/common/__utils/constants.ts
src/controllers/features/update-acsp/whatIsTheBusinessNameController.ts
src/services/common.ts
src/validation/unicorporatedWhatIsTheBusinessName.ts
src/views/common/what-is-the-business-name/what-is-the-business-name.njk
test/src/controllers/updateAcspDetails/whatIsTheBusinessNameController.test.ts

Changes for ticket: 
[IDVA5-2054](https://companieshouse.atlassian.net/browse/IDVA5-2054?atlOrigin=eyJpIjoiNjkwNDQ1MWFmMGRkNGVmYzkwYmNmM2JmYjE5ZmQ2NWYiLCJwIjoiaiJ9)
- Updating Business name validation for Ltd companies
- Adding constant array of limited business types.
- Creating common service that checks if the business type is of limited types.
- Re-using new service function for normalising data for validation
- If no Company name is entered and user attempts to continue as a Ltd company then specific validation is flagged
- When ACSP profiles are approved by CHIPS, the string ‘ACSP’ is appended to the business name, however, we trim this string for display on the front end of our service. 
- Calling getBusinessName function on the existing business name before comparison, which trims …

Updating business name validation and content ltd journey update acsp

---

src/common/__utils/constants.ts
src/common/__utils/sessionHelper.ts
src/controllers/features/update-acsp/amlMembershipNumberController.ts
src/controllers/features/update-acsp/businessAddressConfirmController.ts
src/controllers/features/update-acsp/correspondenceAddressConfirmController.ts
src/controllers/features/update-acsp/dateOfTheChangeController.ts
src/controllers/features/update-acsp/updateYourDetailsController.ts
src/controllers/features/update-acsp/whatIsTheBusinessNameController.ts
src/controllers/features/update-acsp/whatIsYourNameController.ts
src/controllers/features/update-acsp/whereDoYouLiveController.ts
src/controllers/features/update-acsp/yourUpdatesController.ts
src/services/update-acsp/dateOfTheChangeService.ts
src/types/pageURL.ts
test/src/services/update_acsp/dateOfTheChangeService.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-2113
https://companieshouse.atlassian.net/browse/IDVA5-2114
- Removed ACSP_DETAILS_UPDATE_ELEMENT constant and renamed all references to use ACSP_UPDATE_PREVIOUS_PAGE_URL as these values are storing urls and used for navigation back from dateOfChange screen
- For Add AML, I set ACSP_UPDATE_PREVIOUS_PAGE_URL to the AML Membership number screen url (/aml-membership-number) and I check this to set the dateOfChange title.
- For Remove AML, I set the value of ACSP_UPDATE_PREVIOUS_PAGE_URL to the Update Your Details screen url (/update-your-details) as this is the only screen prior to the dateOfChange for the Remove AML flow.
- I delete ACSP_UPDATE_PREVIOUS_PAGE_URL from the session when selecting to either add more updates or submit the updates …

Add/Remove AML date screen title fix and renaming to ACSP_UPDATE_PREVIOUS_PAGE_URL

---

src/views/partials/nav/navbar.njk

Bug fix for ticket:
[IDVA5-2129](https://companieshouse.atlassian.net/browse/IDVA5-2129)
- Removing lang set to i18n within njk file as lang is retrieved from common_variables_middleware.ts file
[IDVA5-2129]: https://companieshouse.atlassian.net/browse/IDVA5-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removing lang set to i18n to allow language to be retained across navbar links

---

locales/cy/your-updates.json
locales/en/your-updates.json
src/views/features/update-acsp-details/your-updates/your-updates.njk
test/src/controllers/updateAcspDetails/yourUpdatesController.test.ts

Fix for ticket:
[IDVA5-2119](https://companieshouse.atlassian.net/browse/IDVA5-2119?atlOrigin=eyJpIjoiMzlmNmEyOTIwMTk4NDVkOGFmMTM1NjI2MWVkMWJmZTMiLCJwIjoiaiJ9)
Also includes changes required for ticket:
[IDVA5-2121](https://companieshouse.atlassian.net/browse/IDVA5-2121)
- Removing 'Changed on' date text on Your Updates screen for Correspondence email address when an update has been made.
- It is no longer a requirement to include the changed on date when updating an email address
- Updating tab heading and page title from `Your Updates` -> `Your updates`
- Updating size of title text for Your updates, from xl to l
[IDVA5-2119]: https://companieshouse.atlassian.net/browse/IDVA5-2119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDVA5-2121]: …

Removing date of change text from email on your updates screen

---

locales/en/aml-body-number.json
src/controllers/features/update-acsp/amlMembershipNumberController.ts
src/controllers/features/update-acsp/updateYourDetailsController.ts
test/src/controllers/updateAcspDetails/amlMembershipNumberController.test.ts

Fixes for AML bug tickets:
[IDVA5-2107](https://companieshouse.atlassian.net/browse/IDVA5-2107)
[IDVA5-2135](https://companieshouse.atlassian.net/browse/IDVA5-2135)
[IDVA5-2107]: https://companieshouse.atlassian.net/browse/IDVA5-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- Exclude validation check to allow users to navigate to the 'When did AML supervision start?' date page only when editing/updating a new AML body that was added, this allows users to keep the existing aml number and make changes to the date entry.
- Validation captures duplicate aml body name/number if the user attempts to add new aml details for an aml that was previously added in ther journey
- Uses the existing AML_REMOVED_BODY_DETAILS session object to check for …

Updating aml validation to allow date of change edits and prevent form submission with no updates

---

src/controllers/features/update-acsp/addAmlSupervisorController.ts
src/controllers/features/update-acsp/amlMembershipNumberController.ts
test/src/controllers/updateAcspDetails/addAmlSupervisorController.test.ts
test/src/controllers/updateAcspDetails/amlMembershipNumberController.test.ts

Modified AML controllers:
-- Added a check if aml details exist in the session before initiating for aml body and aml number controllers.
-- Added the tests.
https://companieshouse.atlassian.net/browse/IDVA5-2161

IDVA5-2161 Retain AML number when pressing back on 'when did this start' screen

---

locales/cy/common.json
locales/en/close-acsp-confirm-you-want-to-close.json
src/middleware/close-acsp/close_variables_middleware.ts

Fixing issue returned from test against ticket:
[IDVA5-1505](https://companieshouse.atlassian.net/browse/IDVA5-1505)
- Updating body text content to match the latest prototype
- **Additional change:** Adding in Welsh translated text for common tab title for close acsp service
- **Bug fix:** Fixing a bug where the language selected was not carried across to Authorised Agent dashboard when pressing 'Cancel' on close-acsp screens
[IDVA5-1505]: https://companieshouse.atlassian.net/browse/IDVA5-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating page content adding welsh content and retaining lang on cancel

---

src/controllers/errorController.ts
test/src/controllers/errorController.test.ts

Ticket [IDVA5-2180](https://companieshouse.atlassian.net/browse/IDVA5-2180)
Updated the error controller when a 401 error is thrown. It now checks to see which service threw the 401 and redirects back to the base url for that service (except the registration service which redirects to check saved applications)
[IDVA5-2180]: https://companieshouse.atlassian.net/browse/IDVA5-2180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating error controllers handling of 401 error redirects

---

src/services/checkYourAnswersService.ts
src/services/common.ts
src/views/features/update-acsp-details/your-updates/your-updates.njk
src/views/partials/your-updates-add-aml.njk
src/views/partials/your-updates-remove-aml.njk
test/src/services/checkYourAnswersService.test.ts
test/src/services/common.test.ts
test/src/services/update_acsp/updateYourDetailsService.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-2140
**Bug:** screen reader was encountering `<br>` tags mainly for formatted addresses in Update ACSP Update Your Details screen which was taking users out of the group and reading 'empty group' every time.
**Changes:** I've replaced `<br>` tags with `<p>` tags using govuk classes to keep the same formatting and spacing as `<br>`.
I also discovered this was happening on every field on the Your Updates screen before the 'Changed on 01 Jan 2025' lines so these `<br>` tags have also been replaced.
As I changed the formatAddressIntoHTMLString function which is also called in Register ACSP service on Check Your Answers screen, the tests for checkYourAnswersService have been updated as well.

Refactor formatAddressIntoHTMLString replacing <br> with <p>

---

src/controllers/features/close-acsp/confirmationAuthorisedAgentClosedController.ts
src/views/features/close-acsp/confirmation-authorised-agent-closed/confirmation-authorised-agent-closed.njk

Fixing issue for ticket returned from testing:
[IDVA5-1759](https://companieshouse.atlassian.net/browse/IDVA5-1759)
- Normalising both login email and correspondence email address before comparison to prevent both displaying on front end screen if there is a difference in letter case (i.e; login email = test@test.com, correspondence email = TEST@TEST.COM)
[IDVA5-1759]: https://companieshouse.atlassian.net/browse/IDVA5-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

normalising email addresses before comparrison on confirmation page

---

src/controllers/features/update-acsp/updateYourDetailsController.ts

https://companieshouse.atlassian.net/browse/IDVA5-2185
**Bug:** Continue/Cancel buttons at bottom of Update Your Details were not showing even after updating any values, Adding AML or Removing AML.
**Fix:** Moved the updateFlag value so it is set first in controller and also checking for !deepEquals

IDVA5-2185 updateFlag value fixed to show/hide continue and cancel button

---

locales/cy/update-acsp-what-is-your-email.json
locales/en/update-acsp-what-is-your-email.json
src/views/features/update-acsp-details/what-is-your-email/what-is-your-email.njk

Changes for ticket:
[IDVA5-2176](https://companieshouse.atlassian.net/browse/IDVA5-2176?atlOrigin=eyJpIjoiOTU5ZWYzZmI0OGY5NDVkZGI2NGEzNDk1YTYyNzMyNTMiLCJwIjoiaiJ9)
Updating content for 'What email address should we use for correspondence?' screen for Update ACSP Details service
[IDVA5-2176]: https://companieshouse.atlassian.net/browse/IDVA5-2176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating content for correspondence email update acsp details

---

locales/cy/aml-body-number.json
locales/cy/common.json
locales/en/address-look-up.json
locales/en/common.json
src/views/common/correspondence-auto-lookup-address/auto-lookup-address.njk
src/views/common/your-responsibilities/your-responsibilities.njk
src/views/features/close-acsp/confirm-you-want-to-close/confirm-you-want-to-close.njk
src/views/features/update-acsp-details/index/home.njk

Changes for bug ticket:
[IDVA5-2204](https://companieshouse.atlassian.net/browse/IDVA5-2204?atlOrigin=eyJpIjoiMmQ5NTQxZTJiOTkwNDM0NmJjYjNmZTViMTY4YjFkZTAiLCJwIjoiaiJ9)
- Updated missing Welsh translations
- Added missing hint text on address auto lookup screens
- Added translation for visually hidden 'Warning' text across Update ACSP and Registration services, as this is required for screen readers
[IDVA5-2204]: https://companieshouse.atlassian.net/browse/IDVA5-2204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating missing Welsh translation

---

src/controllers/features/update-acsp/applicationConfirmationController.ts
src/controllers/indexController.ts
src/middleware/registration_variables_middleware.ts
src/middleware/update-acsp/update_variables_middleware.ts
src/types/pageURL.ts
src/views/features/update-acsp-details/application-confirmation/application-confirmation.njk
src/views/partials/phase_banner.njk

Changes for ticket:
[IDVA5-2207](https://companieshouse.atlassian.net/browse/IDVA5-2207)
- Adding constants for feedback links for both update acsp and registration services
- Assigning above constants to feedbackLink variables in middlewares to be accessible across services (we no longer need the default value as the feedbackLink will not be undefined/null)
- Updating phase_banner.njk to use feedbackLink from middleware
- Adding feedbackLink to confirmation page on update acsp details service
[IDVA5-2207]: https://companieshouse.atlassian.net/browse/IDVA5-2207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding feedback link for update acsp service

---

src/controllers/features/update-acsp/applicationConfirmationController.ts
src/views/features/update-acsp-details/application-confirmation/application-confirmation.njk
src/views/partials/phase_banner.njk

Change for ticket:
[IDVA5-2218](https://companieshouse.atlassian.net/browse/IDVA5-2218)
- Updating confirmation page on Update ACSP Details service to display the logged in user email address rather than the correspondence email address.
- Fixing a visual bug on the href text of the feedback banner
[IDVA5-2218]: https://companieshouse.atlassian.net/browse/IDVA5-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating confirmation page to display users logged in email

---

src/controllers/features/update-acsp/dateOfTheChangeController.ts

The error is thrown by the dateOfTheChangeService.ts due to the AML details for which the date to be added had become undefined at the Your update page. 
The fix is to regenerate the deleted AML details and then add the date to it.

IDVA5-2188 Update ACSP -Getting technical error screen when navigating back from your update screen and click on continue

---

src/app.ts
src/middleware/close-acsp/close_acsp_authentication_middleware.ts
src/middleware/close-acsp/close_acsp_base_authentication_middleware.ts
src/middleware/close-acsp/close_acsp_is_owner_middleware.ts
test/mocks/all_middleware_mock.ts
test/mocks/close_acsp_authentication_middleware_mock.ts
test/src/middleware/close-acsp/close_acsp_authentication_middleware.test.ts
test/src/middleware/close-acsp/close_acsp_base_authentication_middleware.test.ts
test/src/middleware/close-acsp/close_acsp_is_owner_middleware.test.ts

Ticket [IDVA5-2023](https://companieshouse.atlassian.net/browse/IDVA5-2023)
Adding auth middleware to redirect to the close ACSP service when the user logs in.
Previously when the user logged in from close ACSP they would be redirected to registration after they entered their login details. Now the user stays in the Close journey
[IDVA5-2023]: https://companieshouse.atlassian.net/browse/IDVA5-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing Auth redirection for Close ACSP login

---

src/controllers/features/update-acsp/amlMembershipNumberController.ts
src/services/update-acsp/amlMembershipNumberService.ts
src/types/pageURL.ts

https://companieshouse.atlassian.net/browse/IDVA5-2244
**Bug:** back link on AML Membership Number page was redirecting to "/select-aml-supervisor" as there was a duplicate pageUrl which was used for the previousPage value. After we updated this url it was displaying 'Page not found'.
**Fix:** I've removed the duplicate pageUrl and replaced it with "/which-aml-supervisory-body-are-you-registered-with" which was updated to the correct url in both the controller (get method) and service (post method to render if errors are displayed).

Remove duplicate pageUrl and update to use correct one for AML body page

---

src/common/__utils/sessionHelper.ts

Fix for bug:
[IDVA5-2248](https://companieshouse.atlassian.net/browse/IDVA5-2248?atlOrigin=eyJpIjoiNzQxNGRhNTBiMGUyNGRkNTk4ZmNlYzgwMzIyOWUwNjIiLCJwIjoiaiJ9)
- Adding missing temp session data to delete all session data method to ensure all session values are being cleared upon submitting an update ACSP application
[IDVA5-2248]: https://companieshouse.atlassian.net/browse/IDVA5-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding further session data to deleteAllSessionData method

---

src/controllers/features/update-acsp/applicationConfirmationController.ts
src/controllers/features/update-acsp/cancelAllUpdatesController.ts
test/src/controllers/updateAcspDetails/cancelAllUpdatesController.test.ts

There were a redirect and link without the lang parameter, which was causing the issue
-- Added the lang parameter in the controller.
-- Added the lang parameter in the njk through the respective variable.
-- Modified the test cases.

IDVA5-2184 Update ACSP - Welsh toggle is not holding up to Authorised agent dashboard when clicking on Cancel All Updates button 

---

src/controllers/features/close-acsp/indexController.ts
src/utils/properties.ts
src/views/features/close-acsp/index/home.njk

Changes for ticket:
[IDVA5-2217](https://companieshouse.atlassian.net/browse/IDVA5-2217)
- Adding matomo goal for close acsp service, triggers when user clicks the continue button on the index page
[IDVA5-2217]: https://companieshouse.atlassian.net/browse/IDVA5-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding matomo goal to start page of close acsp service

---

src/services/close-acsp/acspCloseService.ts
test/src/services/close-acsp/acspCloseService.test.ts

Fix for ticket:
[IDVA5-1507](https://companieshouse.atlassian.net/browse/IDVA5-1507)
- Saving business name to Close ACSP transaction to allow close acsp email template to populate the company name field
[IDVA5-1507]: https://companieshouse.atlassian.net/browse/IDVA5-1507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding company name to close acsp transaction

---

src/views/features/close-acsp/confirm-you-want-to-close/confirm-you-want-to-close.njk
src/views/features/close-acsp/index/home.njk
src/views/features/close-acsp/what-will-happen/what-will-happen.njk

https://companieshouse.atlassian.net/browse/IDVA5-2280
**Bug:** Cancel links provided no description or context for the user. UCD asked that we replace the 'Cancel' links with 'Go back to authorised agent services' like in Update ACSP.
**Fix:** Replaced 'Cancel' links on 3 screens

Cancel links replaced with Go Back To Authorised Agent Services (Close ACSP)

---

src/common/__utils/constants.ts
src/controllers/features/close-acsp/confirmYouWantToCloseController.ts
src/controllers/features/update-acsp/yourUpdatesController.ts
src/errors/acspCeasedError.ts
src/middleware/close-acsp/close_acsp_get_acsp_profile_middleware.ts
src/middleware/update-acsp/update_acsp_get_acsp_profile_middleware.ts
test/src/controllers/closeAcsp/confirmYouWantToCloseController.test.ts
test/src/controllers/updateAcspDetails/yourUpdatesController.test.ts
test/src/middleware/close-acsp/close_acsp_get_acsp_profile_middleware.test.ts
test/src/middleware/update-acsp/update_acsp_get_acsp_profile_middleware.test.ts

Ticket [IDAV5-2312](https://companieshouse.atlassian.net/browse/IDVA5-2312)
Adding ACSP status check before submitting on close and update journeys. This prevents users of ACSPs who are still logged in after the ACSP is close submitting changes

Adding ACSP status check before submitting

---

src/controllers/features/update-acsp/addAmlSupervisorController.ts
src/controllers/features/update-acsp/businessAddressAutoLookupController.ts
src/controllers/features/update-acsp/cancelAllUpdatesController.ts
src/controllers/features/update-acsp/correspondenceAddressAutoLookupController.ts
src/controllers/features/update-acsp/whatIsTheBusinessNameController.ts
src/controllers/features/update-acsp/whatIsYourEmailAddressController.ts
src/controllers/features/update-acsp/whatIsYourNameController.ts
src/controllers/features/update-acsp/whereDoYouLiveController.ts
test/src/controllers/updateAcspDetails/addAmlSupervisorController.test.ts
test/src/controllers/updateAcspDetails/businessAddressAutoLookupController.test.ts
test/src/controllers/updateAcspDetails/correspondenceAddressAutoLookupController.test.ts
test/src/controllers/updateAcspDetails/whatIsTheBusinessNameController.test.ts
test/src/controllers/updateAcspDetails/whatIsYourNameController.test.ts
test/src/controllers/updateAcspDetails/whereDoYouLiveController.test.ts

Fix for bug:
[IDVA5-2341](https://companieshouse.atlassian.net/browse/IDVA5-2341)
- When making a update to any field (i.e. Business name) ->  removing an existing AML body then editing the previously updated field from your updates (i.e. Business name). This caused the removed AML body details to be cleared from 'Your updates' screen.
- The above bug was occurring as we had not cleared the 2 temp session variables AML_REMOVAL_INDEX, AML_REMOVAL_BODY when choosing to edit the updated field.
- Have added the deletion of these session variables to each controller screen that is called when we choose to edit an existing update to prevent the removed AML details from clearing when returning to 'Your updates'.
- Updated unit tests
[IDVA5-2341]: …

Prevent previously removed AML details clearing from your updates screen

---

locales/cy/must-be-authorised-agent.json
locales/en/must-be-authorised-agent.json
src/app.ts
src/config/index.ts
src/controllers/features/common/mustBeAuthorisedAgentController.ts
src/controllers/index.ts
src/middleware/close-acsp/close_acsp_user_is_part_of_acsp_middleware.ts
src/middleware/update-acsp/update_acsp_user_is_part_of_acsp_middleware.ts
src/routes/closeRoutesAcsp.ts
src/routes/index.ts
src/routes/updateRoutesAcsp.ts
src/types/pageURL.ts
src/views/common/must-be-authorised-agent/must-be-authorised-agent.njk
test/mocks/close_acsp_authentication_middleware_mock.ts
test/mocks/update_acsp_authentication_middleware_mock.ts
test/src/controllers/common/mustBeAuthorisedAgentController.test.ts
test/src/middleware/close-acsp/close_acsp_user_is_part_of_acsp_middleware.test.ts
test/src/middleware/update-acsp/update_acsp_user_is_part_of_acsp_middleware.test.ts

Implemented middleware (for update-acsp and close-acsp) that checks if a user is part of an ACSP and added tests.
Introduced JSON, njk, and ts files for new kickout screen and added tests.
Wired up new kickout screen to router and redirect call from middleware to screen.
Excluded kickout screen from middleware that errors if a user is not associated with an ACSP.
**JIRA Ticket**
https://companieshouse.atlassian.net/browse/IDVA5-2031

Kickout screen when user is not a part of an ACSP

---

src/common/__utils/constants.ts
src/controllers/features/common/otherTypeOfBusinessController.ts
src/controllers/features/common/typeOfBusinessController.ts
test/src/controllers/common/otherTypeOfBusinessController.test.ts

https://companieshouse.atlassian.net/browse/IDVA5-2352
The same check which was added to Type Of Business screen, to check for saved applications and redirect user accordingly if they access the url directly, has now been added to the Other Type Of Business screen as we also create a new transaction  here.
I am using the flag TYPE_OF_BUSINESS_SELECTED which is set on Type Of Business screen to determine whether to redirect the user or not, since in some cases the redirect will be to the Type Of Business screen again creating a loop. Once they continue past the Other Type Of Business screen this is deleted from the session.

Added check for saved applications for Other Business Type screen

---

src/services/checkSavedApplicationService.ts
test/src/services/checkSavedApplicationService.test.ts

IDVA5-2397 Register an ACSP - Allow Previously Registered ACSP Member to Register a New ACSP
-- Modified the logic to check the existence of the acsp number from the signed in details
-- Added the tests
https://companieshouse.atlassian.net/browse/IDVA5-2397

IDVA5-2397 Register an ACSP - Allow Previously Registered ACSP Member to Register a New ACSP

---

src/views/common/check-aml-details/check-aml-details.njk
src/views/common/what-is-your-role/what-is-your-role.njk
src/views/features/update-acsp-details/your-updates/your-updates.njk
src/views/partials/update-your-details/limited-answers.njk
src/views/partials/update-your-details/sole-trader-answers.njk
src/views/partials/update-your-details/unincorporated-answers.njk

Fix for bug ticket:
[IDVA5-2516](https://companieshouse.atlassian.net/browse/IDVA5-2516)
This fix allows Angle brackets to be displayed in areas where we construct text using concatenated html macros.
This follows the recent changes that allows angle brackets to be accepted for business/company names.
Previously business/company names were not rendering their string values on certain screens if the business name was valid and contained angle brackets (i.e. if a company is named `<b>`, `<abc>`, `<i>` etc) as nunjucks was treating these as html values.
This includes fixes for correct display of angle brackets on the following screens.
Update ACSP Details -> Authorised agent's details (Main screen)
Update ACSP Details -> Your updates
Registration service -> What is your role -> this fixes …

Escaping business and company name values to allow angle bracket display

---

src/middleware/content_security_policy_middleware_config.ts

PIWIK_CHS_DOMAIN env var stores value: `*.cidev.aws.chdev.org`. Testing with hardcoded value with `https://` added.
Also adding `https://*.company-information.service.gov.uk` into the formActionDirective for other page not just homepage to test if another page needs it to redirect correctly.

IDVA5-2592 Replace PIWIK_CHS_DOMAIN with hardcoded value with protocol added for testing

---

src/middleware/content_security_policy_middleware_config.ts

Adding hardcoded urls from console for testing:
```
"https://cidev.aws.chdev.org/register-as-companies-house-authorised-agent",
"https://cidev.aws.chdev.org/register-as-companies-house-authorised-agent?lang=en"
```

IDVA5-2592 Adding hardcoded urls from console to CSP for testing

---

locales/en/cookie-consent-banner.json
package-lock.json
package.json
src/middleware/content_security_policy_middleware_config.ts
src/views/common/sign-out-page/sign-out.njk
src/views/features/sole-trader/where-do-you-live/where-do-you-live.njk
src/views/layouts/default.njk
src/views/partials/__footer.njk
src/views/partials/__meta_footer.njk
src/views/partials/cookie_consent_banner.njk
src/views/partials/nav/back_link.njk
src/views/partials/nav/navbar.njk
src/views/partials/nav/signout-bar.njk
src/views/partials/phase_banner.njk

Updates made to ACSP web applications against the following tickets returned from testing:
[IDVA5-2553](https://companieshouse.atlassian.net/browse/IDVA5-2553)
[IDVA5-2454](https://companieshouse.atlassian.net/browse/IDVA5-2454)
- It was flagged during testing that previously the 'beta' tag element was styled differently (bold text, all uppercase). It is now intentional by design that these tag elements no longer follow the same design (no longer bold and all uppercase):
[GDS - Tag](https://design-system.service.gov.uk/components/tag/)
[GDS - Phase Banner](https://design-system.service.gov.uk/components/phase-banner/)
-----------------
- Fixed an issue with padding on the <main> tag element, that was causing a gap between the header and the main page content of the application.
**Update …

Fixing display issues against govuk branding 5.11

---

src/middleware/content_security_policy_middleware_config.ts

Added GOV_UK = "https://*.gov.uk" to CSP for default to allow sign out button redirect to work correctly to allow following redirect from response header:
`https://oidc.integration.account.gov.uk/logout?`

Adding gov.uk domains to default CSP to fix signout issue

---

locales/cy/start-page.json
locales/en/start-page.json

Ticket:
[IDVA5-2658](https://companieshouse.atlassian.net/browse/IDVA5-2658)
- Removing text 'The service to tell us when you’ve verified someone’s identity will be available soon.' from Registration start screen for English and Welsh locales files
[IDVA5-2658]: https://companieshouse.atlassian.net/browse/IDVA5-2658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating start page content
